@baseUrl = https://chris-devbox.phl.io/functions/v1
@token = YOUR_TOKEN_HERE

###

GET {{baseUrl}}/db-test

### Send friend request

POST {{baseUrl}}/send-friend-request
Content-Type: application/json
Authorization: Bearer {{token}}

    {
        "phone": "15556667777"
    }


### Respond to friend request

POST {{baseUrl}}/action-friend-request
Content-Type: application/json
Authorization: Bearer {{token}}

    {
        "friend_id": "FRIEND_UUID",
        "action": "declined"
    }


### RSVP to event

POST {{baseUrl}}/rsvp
Content-Type: application/json
Authorization: Bearer {{token}}

    {
        "instance_id": "INSTANCE_UUID",
        "status": "maybe"
    }



### Invite friends to an event

POST {{baseUrl}}/invite
Content-Type: application/json
Authorization: Bearer {{token}}

    {
        "instance_id": "INSTANCE_UUID",
        "users": [
            "FRIEND_UUID",
            "FRIEND_UUID_1"
        ]
    }
