###

GET {{baseUrl}}/db-test

### Send friend request

POST {{baseUrl}}/send-friend-request
Content-Type: application/json
Authorization: Bearer {{token}}

    {
        "phone": "{{jarvus_userPhone}}",
        "first_name": "Benjamin",
        "last_name": "Franklin"
    }


### Respond to friend request

POST {{baseUrl}}/action-friend-request
Content-Type: application/json
Authorization: Bearer {{token}}

    {
        "friend_id": "{{friendId}}",
        "action": "declined"
    }


### RSVP to event

POST {{baseUrl}}/rsvp
Content-Type: application/json
Authorization: Bearer {{token}}

    {
        "instance_id": "{{instanceId}}",
        "status": "omw"
    }



### Invite friends to an event

POST {{baseUrl}}/invite
Content-Type: application/json
Authorization: Bearer {{token}}

    {
        "instance_id": "{{instanceId}}",
        "users": [
            "{{friendId}}",
            "{{friend2Id}}"
        ]
    }

### Push test

POST {{baseUrl}}/push-test
Content-Type: application/json
Authorization: Bearer {{token}}

    {
        "type": "INSERT",
        "schema": "public",
        "table": "notifications",
        "record": {
            "id": "PLACEHOLDER_ID",
            "user_id": "{{userId}}",
            "body": "Hello World!"
        }
    }


### Get friend profile

GET {{baseUrl}}/get-friend-profile
    ?user_id={{userId}}
Authorization: Bearer {{token}}

### Get friend network

GET {{baseUrl}}/get-friends-network
Authorization: Bearer {{token}}


### Trigger: INSERT profile

POST {{baseUrl}}/on-profile-insert
Content-Type: application/json
Authorization: Bearer {{token}}

    {
        "type": "INSERT",
        "table": "profiles",
        "schema": "public",
        "old_record": null,
        "record": {
            "id": "8ea503ff-403a-4d1d-8a0d-25df32476590",
            "phone": "12152598338",
            "photo": null,
            "fcm_token": null,
            "last_name": "Franklin",
            "first_name": "Benjamin",
            "fcm_token_app_build": null,
            "fcm_token_updated_at": null
        }
    }

### Get profile

GET {{baseUrl}}/get-profile
    ?phone={{userPhone}}
Authorization: Bearer {{token}}


### Scrape Facebook event

GET {{baseUrl}}/scrape-facebook-event
    ?url=https%3A%2F%2Fwww.facebook.com%2Fevents%2Fs%2Faugust-19th-philly-full-moon-r%2F1188917002238256%2F
Authorization: Bearer {{token}}
