@baseUrl = https://chris-devbox.phl.io/functions/v1
@token = YOUR_TOKEN_HERE

###

GET {{baseUrl}}/db-test

### Send friend request

POST {{baseUrl}}/friend-request
Content-Type: application/json
Authorization: Bearer {{token}}

    {
        "phone": "15556667777"
    }
