/**
 * TEMPLATE — adapt by replacing `appstore` / `MYTOOL` with your CLI name, and the
 * entry/outfile paths with your layout. (Single-skill form shown; for a
 * multi-skill repo, replace OUTFILE with a TARGETS array and loop — see the
 * skill's build-pipeline.md.)
 *
 * Build the self-contained bundle committed at ../../.claude/skills/appstore/scripts/appstore.mjs.
 * All dependencies (axi-sdk-js, @toon-format/toon, …) are inlined so the artifact
 * runs under plain `node` ≥ 20 on a machine that only has the skill installed —
 * no npm install, no node_modules. This is what makes the skill drop-in.
 *
 *   bun scripts/build-cli.ts            # write the bundle
 *   bun scripts/build-cli.ts --check    # fail if the committed bundle is stale
 *
 * The CLI version is injected from `git describe`. Because committing the bundle
 * changes the git sha (and CI checkouts may lack tags), --check normalizes the
 * embedded version line out before comparing, so version drift never fails the
 * check while any real src/cli/ change still does.
 */
import * as esbuild from "esbuild";
import { readFileSync, chmodSync } from "node:fs";
import { execSync } from "node:child_process";

const OUTFILE = "../../.claude/skills/appstore/scripts/appstore.mjs";
const check = process.argv.includes("--check");

function gitVersion(): string {
  try {
    return execSync("git describe --tags --always", { encoding: "utf8" }).trim() || "dev";
  } catch {
    return "dev";
  }
}

/**
 * Replace the embedded version literal so --check ignores version drift.
 * Tune this regex to however your VERSION line compiles in the bundle; the
 * default matches `… ? "v1.2.3" : "dev"`.
 */
function normalizeVersion(source: string): string {
  return source.replace(/"[^"]*" : "dev"/, '"__VERSION__" : "dev"');
}

const result = await esbuild.build({
  entryPoints: ["src/cli/bin.ts"],
  outfile: OUTFILE,
  bundle: true,
  platform: "node",
  format: "esm",
  target: "node20",
  legalComments: "none",
  define: { __APPSTORE_VERSION__: JSON.stringify(gitVersion()) },
  banner: {
    js: "#!/usr/bin/env node\n// GENERATED by scripts/build-cli.ts from src/cli/ — do not edit. Run `bun run build`.",
  },
  write: !check,
});

if (check) {
  const generated = result.outputFiles![0]!.text;
  const committed = readFileSync(OUTFILE, "utf8");
  if (normalizeVersion(generated) !== normalizeVersion(committed)) {
    console.error(`${OUTFILE} is out of date — run \`bun run build\` and commit the result`);
    process.exit(1);
  }
  console.log(`${OUTFILE} is up to date`);
} else {
  chmodSync(OUTFILE, 0o755);
  console.log(`Wrote ${OUTFILE}`);
}
