#!/usr/bin/env node
// GENERATED by scripts/build-cli.ts from src/cli/ — do not edit. Run `bun run build`.

// node_modules/axi-sdk-js/dist/cli.js
import { basename as basename2 } from "node:path";

// node_modules/axi-sdk-js/dist/errors.js
var AxiError = class extends Error {
  code;
  suggestions;
  constructor(message, code, suggestions = []) {
    super(message);
    this.code = code;
    this.suggestions = suggestions;
    this.name = "AxiError";
  }
};
function exitCodeForError(error) {
  if (error instanceof AxiError && error.code === "VALIDATION_ERROR") {
    return 2;
  }
  return 1;
}

// node_modules/axi-sdk-js/dist/output.js
import { homedir } from "node:os";

// node_modules/axi-sdk-js/node_modules/@toon-format/toon/dist/index.mjs
var NULL_LITERAL = "null";
var DELIMITERS = {
  comma: ",",
  tab: "	",
  pipe: "|"
};
var DEFAULT_DELIMITER = DELIMITERS.comma;
function escapeString(value) {
  return value.replace(/\\/g, `\\\\`).replace(/"/g, `\\"`).replace(/\n/g, `\\n`).replace(/\r/g, `\\r`).replace(/\t/g, `\\t`).replace(/[\u0000-\u001F]/g, (c) => `\\u${c.charCodeAt(0).toString(16).padStart(4, "0")}`);
}
function isBooleanOrNullLiteral(token2) {
  return token2 === "true" || token2 === "false" || token2 === "null";
}
function setOwnProperty(target, key, value) {
  if (key === "__proto__") {
    Object.defineProperty(target, key, {
      value,
      enumerable: true,
      writable: true,
      configurable: true
    });
    return;
  }
  target[key] = value;
}
function normalizeValue(value) {
  if (value === null) return null;
  if (typeof value === "object" && value !== null && "toJSON" in value && typeof value.toJSON === "function") {
    const next = value.toJSON();
    if (next !== value) return normalizeValue(next);
  }
  if (typeof value === "string" || typeof value === "boolean") return value;
  if (typeof value === "number") {
    if (Object.is(value, -0)) return 0;
    if (!Number.isFinite(value)) return null;
    return value;
  }
  if (typeof value === "bigint") {
    if (value >= Number.MIN_SAFE_INTEGER && value <= Number.MAX_SAFE_INTEGER) return Number(value);
    return value.toString();
  }
  if (value instanceof Date) return value.toISOString();
  if (Array.isArray(value)) return value.map(normalizeValue);
  if (value instanceof Set) return Array.from(value).map(normalizeValue);
  if (value instanceof Map) return Object.fromEntries(Array.from(value, ([k, v]) => [String(k), normalizeValue(v)]));
  if (isPlainObject(value)) {
    const encodedValues = {};
    for (const key in value) if (Object.hasOwn(value, key)) setOwnProperty(encodedValues, key, normalizeValue(value[key]));
    return encodedValues;
  }
  return null;
}
function isJsonPrimitive(value) {
  return value === null || typeof value === "string" || typeof value === "number" || typeof value === "boolean";
}
function isJsonArray(value) {
  return Array.isArray(value);
}
function isJsonObject(value) {
  return value !== null && typeof value === "object" && !Array.isArray(value);
}
function isEmptyObject(value) {
  return Object.keys(value).length === 0;
}
function isPlainObject(value) {
  if (value === null || typeof value !== "object") return false;
  const prototype = Object.getPrototypeOf(value);
  return prototype === null || prototype === Object.prototype;
}
function isArrayOfPrimitives(value) {
  return value.length === 0 || value.every((item) => isJsonPrimitive(item));
}
function isArrayOfArrays(value) {
  return value.length === 0 || value.every((item) => isJsonArray(item));
}
function isArrayOfObjects(value) {
  return value.length === 0 || value.every((item) => isJsonObject(item));
}
var NUMERIC_LIKE_PATTERN = /^-?\d+(?:\.\d+)?(?:e[+-]?\d+)?$/i;
var LEADING_ZERO_PATTERN = /^0\d+$/;
function isValidUnquotedKey(key) {
  return /^[A-Z_][\w.]*$/i.test(key);
}
function isIdentifierSegment(key) {
  return /^[A-Z_]\w*$/i.test(key);
}
function isSafeUnquoted(value, delimiter2 = DEFAULT_DELIMITER) {
  if (!value) return false;
  if (value !== value.trim()) return false;
  if (isBooleanOrNullLiteral(value) || isNumericLike(value)) return false;
  if (value.includes(":")) return false;
  if (value.includes('"') || value.includes("\\")) return false;
  if (/[[\]{}]/.test(value)) return false;
  if (/[\u0000-\u001F]/.test(value)) return false;
  if (value.includes(delimiter2)) return false;
  if (value.startsWith("-")) return false;
  return true;
}
function isNumericLike(value) {
  return NUMERIC_LIKE_PATTERN.test(value) || LEADING_ZERO_PATTERN.test(value);
}
var QUOTED_KEY_MARKER = Symbol("quotedKey");
function tryFoldKeyChain(key, value, siblings, options, rootLiteralKeys, pathPrefix, flattenDepth) {
  if (options.keyFolding !== "safe") return;
  if (!isJsonObject(value)) return;
  const { segments, tail, leafValue } = collectSingleKeyChain(key, value, flattenDepth ?? options.flattenDepth);
  if (segments.length < 2) return;
  if (!segments.every((seg) => isIdentifierSegment(seg))) return;
  const foldedKey = buildFoldedKey(segments);
  const absolutePath = pathPrefix ? `${pathPrefix}.${foldedKey}` : foldedKey;
  if (siblings.includes(foldedKey)) return;
  if (rootLiteralKeys && rootLiteralKeys.has(absolutePath)) return;
  return {
    foldedKey,
    remainder: tail,
    leafValue,
    segmentCount: segments.length
  };
}
function collectSingleKeyChain(startKey, startValue, maxDepth) {
  const segments = [startKey];
  let currentValue = startValue;
  while (segments.length < maxDepth) {
    if (!isJsonObject(currentValue)) break;
    const keys = Object.keys(currentValue);
    if (keys.length !== 1) break;
    const nextKey = keys[0];
    const nextValue = currentValue[nextKey];
    segments.push(nextKey);
    currentValue = nextValue;
  }
  if (!isJsonObject(currentValue) || isEmptyObject(currentValue)) return {
    segments,
    tail: void 0,
    leafValue: currentValue
  };
  return {
    segments,
    tail: currentValue,
    leafValue: currentValue
  };
}
function buildFoldedKey(segments) {
  return segments.join(".");
}
function encodePrimitive(value, delimiter2) {
  if (value === null) return NULL_LITERAL;
  if (typeof value === "boolean") return String(value);
  if (typeof value === "number") return String(value);
  return encodeStringLiteral(value, delimiter2);
}
function encodeStringLiteral(value, delimiter2 = DEFAULT_DELIMITER) {
  if (isSafeUnquoted(value, delimiter2)) return value;
  return `"${escapeString(value)}"`;
}
function encodeKey(key) {
  if (isValidUnquotedKey(key)) return key;
  return `"${escapeString(key)}"`;
}
function encodeAndJoinPrimitives(values, delimiter2 = DEFAULT_DELIMITER) {
  return values.map((v) => encodePrimitive(v, delimiter2)).join(delimiter2);
}
function formatHeader(length, options) {
  const key = options?.key;
  const fields = options?.fields;
  const delimiter2 = options?.delimiter ?? ",";
  let header = "";
  if (key != null) header += encodeKey(key);
  header += `[${length}${delimiter2 !== DEFAULT_DELIMITER ? delimiter2 : ""}]`;
  if (fields) {
    const quotedFields = fields.map((f) => encodeKey(f));
    header += `{${quotedFields.join(delimiter2)}}`;
  }
  header += ":";
  return header;
}
function* encodeJsonValue(value, options, depth) {
  if (isJsonPrimitive(value)) {
    const encodedPrimitive = encodePrimitive(value, options.delimiter);
    if (encodedPrimitive !== "") yield encodedPrimitive;
    return;
  }
  if (isJsonArray(value)) yield* encodeArrayLines(void 0, value, depth, options);
  else if (isJsonObject(value)) yield* encodeObjectLines(value, depth, options);
}
function* encodeObjectLines(value, depth, options, rootLiteralKeys, pathPrefix, remainingDepth) {
  const keys = Object.keys(value);
  if (depth === 0 && !rootLiteralKeys) rootLiteralKeys = new Set(keys.filter((k) => k.includes(".")));
  const effectiveFlattenDepth = remainingDepth ?? options.flattenDepth;
  for (const [key, val] of Object.entries(value)) yield* encodeKeyValuePairLines(key, val, depth, options, keys, rootLiteralKeys, pathPrefix, effectiveFlattenDepth);
}
function* encodeKeyValuePairLines(key, value, depth, options, siblings, rootLiteralKeys, pathPrefix, flattenDepth) {
  const currentPath = pathPrefix ? `${pathPrefix}.${key}` : key;
  const effectiveFlattenDepth = flattenDepth ?? options.flattenDepth;
  if (options.keyFolding === "safe" && siblings) {
    const foldResult = tryFoldKeyChain(key, value, siblings, options, rootLiteralKeys, pathPrefix, effectiveFlattenDepth);
    if (foldResult) {
      const { foldedKey, remainder, leafValue, segmentCount } = foldResult;
      const encodedFoldedKey = encodeKey(foldedKey);
      if (remainder === void 0) {
        if (isJsonPrimitive(leafValue)) {
          yield indentedLine(depth, `${encodedFoldedKey}: ${encodePrimitive(leafValue, options.delimiter)}`, options.indent);
          return;
        } else if (isJsonArray(leafValue)) {
          yield* encodeArrayLines(foldedKey, leafValue, depth, options);
          return;
        } else if (isJsonObject(leafValue) && isEmptyObject(leafValue)) {
          yield indentedLine(depth, `${encodedFoldedKey}:`, options.indent);
          return;
        }
      }
      if (isJsonObject(remainder)) {
        yield indentedLine(depth, `${encodedFoldedKey}:`, options.indent);
        const remainingDepth = effectiveFlattenDepth - segmentCount;
        const foldedPath = pathPrefix ? `${pathPrefix}.${foldedKey}` : foldedKey;
        yield* encodeObjectLines(remainder, depth + 1, options, rootLiteralKeys, foldedPath, remainingDepth);
        return;
      }
    }
  }
  const encodedKey = encodeKey(key);
  if (isJsonPrimitive(value)) yield indentedLine(depth, `${encodedKey}: ${encodePrimitive(value, options.delimiter)}`, options.indent);
  else if (isJsonArray(value)) yield* encodeArrayLines(key, value, depth, options);
  else if (isJsonObject(value)) {
    yield indentedLine(depth, `${encodedKey}:`, options.indent);
    if (!isEmptyObject(value)) yield* encodeObjectLines(value, depth + 1, options, rootLiteralKeys, currentPath, effectiveFlattenDepth);
  }
}
function* encodeArrayLines(key, value, depth, options) {
  if (value.length === 0) {
    yield indentedLine(depth, key != null ? `${encodeKey(key)}: []` : "[]", options.indent);
    return;
  }
  if (isArrayOfPrimitives(value)) {
    yield indentedLine(depth, encodeInlineArrayLine(value, options.delimiter, key), options.indent);
    return;
  }
  if (isArrayOfArrays(value)) {
    if (value.every((arr) => isArrayOfPrimitives(arr))) {
      yield* encodeArrayOfArraysAsListItemsLines(key, value, depth, options);
      return;
    }
  }
  if (isArrayOfObjects(value)) {
    const header = extractTabularHeader(value);
    if (header) yield* encodeArrayOfObjectsAsTabularLines(key, value, header, depth, options);
    else yield* encodeMixedArrayAsListItemsLines(key, value, depth, options);
    return;
  }
  yield* encodeMixedArrayAsListItemsLines(key, value, depth, options);
}
function* encodeArrayOfArraysAsListItemsLines(prefix, values, depth, options) {
  yield indentedLine(depth, formatHeader(values.length, {
    key: prefix,
    delimiter: options.delimiter
  }), options.indent);
  for (const arr of values) if (isArrayOfPrimitives(arr)) {
    const arrayLine = encodeInlineArrayLine(arr, options.delimiter);
    yield indentedListItem(depth + 1, arrayLine, options.indent);
  }
}
function encodeInlineArrayLine(values, delimiter2, prefix) {
  const header = formatHeader(values.length, {
    key: prefix,
    delimiter: delimiter2
  });
  const joinedValue = encodeAndJoinPrimitives(values, delimiter2);
  if (values.length === 0) return header;
  return `${header} ${joinedValue}`;
}
function* encodeArrayOfObjectsAsTabularLines(prefix, rows, header, depth, options) {
  yield indentedLine(depth, formatHeader(rows.length, {
    key: prefix,
    fields: header,
    delimiter: options.delimiter
  }), options.indent);
  yield* writeTabularRowsLines(rows, header, depth + 1, options);
}
function extractTabularHeader(rows) {
  if (rows.length === 0) return;
  const firstRow = rows[0];
  const firstKeys = Object.keys(firstRow);
  if (firstKeys.length === 0) return;
  if (isTabularArray(rows, firstKeys)) return firstKeys;
}
function isTabularArray(rows, header) {
  for (const row of rows) {
    if (Object.keys(row).length !== header.length) return false;
    for (const key of header) {
      if (!Object.hasOwn(row, key)) return false;
      if (!isJsonPrimitive(row[key])) return false;
    }
  }
  return true;
}
function* writeTabularRowsLines(rows, header, depth, options) {
  for (const row of rows) yield indentedLine(depth, encodeAndJoinPrimitives(header.map((key) => row[key]), options.delimiter), options.indent);
}
function* encodeMixedArrayAsListItemsLines(prefix, items, depth, options) {
  yield indentedLine(depth, formatHeader(items.length, {
    key: prefix,
    delimiter: options.delimiter
  }), options.indent);
  for (const item of items) yield* encodeListItemValueLines(item, depth + 1, options);
}
function* encodeObjectAsListItemLines(obj, depth, options) {
  if (isEmptyObject(obj)) {
    yield indentedLine(depth, "-", options.indent);
    return;
  }
  const entries = Object.entries(obj);
  const [firstKey, firstValue] = entries[0];
  const restEntries = entries.slice(1);
  if (isJsonArray(firstValue) && isArrayOfObjects(firstValue)) {
    const header = extractTabularHeader(firstValue);
    if (header) {
      yield indentedListItem(depth, formatHeader(firstValue.length, {
        key: firstKey,
        fields: header,
        delimiter: options.delimiter
      }), options.indent);
      yield* writeTabularRowsLines(firstValue, header, depth + 2, options);
      if (restEntries.length > 0) yield* encodeObjectLines(Object.fromEntries(restEntries), depth + 1, options);
      return;
    }
  }
  const encodedKey = encodeKey(firstKey);
  if (isJsonPrimitive(firstValue)) yield indentedListItem(depth, `${encodedKey}: ${encodePrimitive(firstValue, options.delimiter)}`, options.indent);
  else if (isJsonArray(firstValue)) if (firstValue.length === 0) yield indentedListItem(depth, `${encodedKey}: []`, options.indent);
  else if (isArrayOfPrimitives(firstValue)) yield indentedListItem(depth, `${encodedKey}${encodeInlineArrayLine(firstValue, options.delimiter)}`, options.indent);
  else {
    yield indentedListItem(depth, `${encodedKey}${formatHeader(firstValue.length, { delimiter: options.delimiter })}`, options.indent);
    for (const item of firstValue) yield* encodeListItemValueLines(item, depth + 2, options);
  }
  else if (isJsonObject(firstValue)) {
    yield indentedListItem(depth, `${encodedKey}:`, options.indent);
    if (!isEmptyObject(firstValue)) yield* encodeObjectLines(firstValue, depth + 2, options);
  }
  if (restEntries.length > 0) yield* encodeObjectLines(Object.fromEntries(restEntries), depth + 1, options);
}
function* encodeListItemValueLines(value, depth, options) {
  if (isJsonPrimitive(value)) yield indentedListItem(depth, encodePrimitive(value, options.delimiter), options.indent);
  else if (isJsonArray(value)) if (isArrayOfPrimitives(value)) yield indentedListItem(depth, encodeInlineArrayLine(value, options.delimiter), options.indent);
  else {
    yield indentedListItem(depth, formatHeader(value.length, { delimiter: options.delimiter }), options.indent);
    for (const item of value) yield* encodeListItemValueLines(item, depth + 1, options);
  }
  else if (isJsonObject(value)) yield* encodeObjectAsListItemLines(value, depth, options);
}
function indentedLine(depth, content, indentSize) {
  return " ".repeat(indentSize * depth) + content;
}
function indentedListItem(depth, content, indentSize) {
  return indentedLine(depth, "- " + content, indentSize);
}
function applyReplacer(root, replacer) {
  const replacedRoot = replacer("", root, []);
  if (replacedRoot === void 0) return transformChildren(root, replacer, []);
  return transformChildren(normalizeValue(replacedRoot), replacer, []);
}
function transformChildren(value, replacer, path) {
  if (isJsonObject(value)) return transformObject(value, replacer, path);
  if (isJsonArray(value)) return transformArray(value, replacer, path);
  return value;
}
function transformObject(obj, replacer, path) {
  const result = {};
  for (const [key, value] of Object.entries(obj)) {
    const childPath = [...path, key];
    const replacedValue = replacer(key, value, childPath);
    if (replacedValue === void 0) continue;
    setOwnProperty(result, key, transformChildren(normalizeValue(replacedValue), replacer, childPath));
  }
  return result;
}
function transformArray(arr, replacer, path) {
  const result = [];
  for (let i = 0; i < arr.length; i++) {
    const value = arr[i];
    const childPath = [...path, i];
    const replacedValue = replacer(String(i), value, childPath);
    if (replacedValue === void 0) continue;
    const normalizedValue = normalizeValue(replacedValue);
    result.push(transformChildren(normalizedValue, replacer, childPath));
  }
  return result;
}
function encode(input, options) {
  return Array.from(encodeLines(input, options)).join("\n");
}
function encodeLines(input, options) {
  const normalizedValue = normalizeValue(input);
  const resolvedOptions = resolveOptions(options);
  return encodeJsonValue(resolvedOptions.replacer ? applyReplacer(normalizedValue, resolvedOptions.replacer) : normalizedValue, resolvedOptions, 0);
}
function resolveOptions(options) {
  return {
    indent: options?.indent ?? 2,
    delimiter: options?.delimiter ?? DEFAULT_DELIMITER,
    keyFolding: options?.keyFolding ?? "off",
    flattenDepth: options?.flattenDepth ?? Number.POSITIVE_INFINITY,
    replacer: options?.replacer
  };
}

// node_modules/axi-sdk-js/dist/output.js
function collapseHomeDirectory(path, homeDir = homedir()) {
  if (!path.startsWith(homeDir)) {
    return path;
  }
  return `~${path.slice(homeDir.length)}`;
}
function homeHeaderOutput(options) {
  return {
    bin: collapseHomeDirectory(options.execPath ?? process.argv[1] ?? "", options.homeDir),
    description: options.description
  };
}
function errorOutput(message, code, suggestions = []) {
  const output = {
    error: message,
    code
  };
  if (suggestions.length > 0) {
    output.help = suggestions;
  }
  return output;
}
function renderOutput(output) {
  if (typeof output === "string") {
    return output;
  }
  return encode(output);
}
function renderError(message, code, suggestions = []) {
  return renderOutput(errorOutput(message, code, suggestions));
}

// node_modules/axi-sdk-js/dist/update.js
import { spawn } from "node:child_process";
import { execFile } from "node:child_process";
import { existsSync, readFileSync, realpathSync } from "node:fs";
import { basename, dirname, join } from "node:path";
import { promisify } from "node:util";
var execFileAsync = promisify(execFile);
var REGISTRY_BASE = "https://registry.npmjs.org";
var REGISTRY_FETCH_TIMEOUT_MS = 2e4;
function parseSemver(version) {
  const match = /^v?(\d+)\.(\d+)\.(\d+)(?:-([0-9A-Za-z-.]+))?(?:\+[0-9A-Za-z-.]+)?$/.exec(version.trim());
  if (!match) {
    return null;
  }
  return {
    major: Number(match[1]),
    minor: Number(match[2]),
    patch: Number(match[3]),
    prerelease: match[4] ? match[4].split(".") : []
  };
}
function comparePrerelease(a, b) {
  if (a.length === 0 && b.length === 0)
    return 0;
  if (a.length === 0)
    return 1;
  if (b.length === 0)
    return -1;
  const length = Math.max(a.length, b.length);
  for (let index = 0; index < length; index += 1) {
    if (index >= a.length)
      return -1;
    if (index >= b.length)
      return 1;
    const left = a[index];
    const right = b[index];
    const leftNumeric = /^\d+$/.test(left);
    const rightNumeric = /^\d+$/.test(right);
    if (leftNumeric && rightNumeric) {
      const delta = Number(left) - Number(right);
      if (delta !== 0)
        return delta < 0 ? -1 : 1;
    } else if (leftNumeric) {
      return -1;
    } else if (rightNumeric) {
      return 1;
    } else if (left !== right) {
      return left < right ? -1 : 1;
    }
  }
  return 0;
}
function compareSemver(a, b) {
  const parsedA = parseSemver(a);
  const parsedB = parseSemver(b);
  if (!parsedA || !parsedB) {
    if (a === b)
      return 0;
    return a < b ? -1 : 1;
  }
  if (parsedA.major !== parsedB.major) {
    return parsedA.major < parsedB.major ? -1 : 1;
  }
  if (parsedA.minor !== parsedB.minor) {
    return parsedA.minor < parsedB.minor ? -1 : 1;
  }
  if (parsedA.patch !== parsedB.patch) {
    return parsedA.patch < parsedB.patch ? -1 : 1;
  }
  return comparePrerelease(parsedA.prerelease, parsedB.prerelease);
}
function isUpdateAvailable(current, latest) {
  return compareSemver(latest, current) > 0;
}
var nodeFs = {
  existsSync,
  readFileSync: (path, encoding) => readFileSync(path, encoding)
};
function readNearestPackageJson(startPath, fs = nodeFs) {
  let dir = dirname(startPath);
  let previous = "";
  while (dir !== previous) {
    const packageJsonPath = join(dir, "package.json");
    if (fs.existsSync(packageJsonPath)) {
      try {
        const parsed = JSON.parse(fs.readFileSync(packageJsonPath, "utf-8"));
        if (typeof parsed.name === "string" && parsed.name.length > 0) {
          return {
            packageName: parsed.name,
            version: typeof parsed.version === "string" ? parsed.version : void 0,
            packageJsonPath
          };
        }
      } catch {
      }
    }
    previous = dir;
    dir = dirname(dir);
  }
  return {};
}
function detectInstallMethod(options) {
  const env = options.env ?? process.env;
  const path = options.entry.replaceAll("\\", "/");
  if (path.includes("/_npx/") || /\/dlx-[^/]+\//.test(path) || path.includes("/pnpm/dlx/") || path.includes("/bun/install/cache/")) {
    return { kind: "npx" };
  }
  const homebrewFormula = homebrewFormulaFromPath(path, env);
  if (homebrewFormula) {
    return { kind: "homebrew", formula: homebrewFormula };
  }
  const pnpmHome = normalizePathRoot(env.PNPM_HOME);
  if (isPathInsideRoot(path, pnpmHome) || isKnownPnpmGlobalStore(path, env)) {
    return { kind: "pnpm-global" };
  }
  if (isKnownNpmGlobalInstall(path, env)) {
    return { kind: "npm-global" };
  }
  return { kind: "unknown" };
}
function normalizePathRoot(path) {
  const normalized = path?.replaceAll("\\", "/").replace(/\/+$/, "");
  return normalized && normalized.length > 0 ? normalized : void 0;
}
function isPathInsideRoot(path, root) {
  return root !== void 0 && (path === root || path.startsWith(`${root}/`));
}
function homebrewFormulaFromPath(path, env) {
  for (const root of homebrewCellarRoots(env)) {
    if (!isPathInsideRoot(path, root)) {
      continue;
    }
    const relative = path.slice(root.length).replace(/^\/+/, "");
    const formula = relative.split("/")[0];
    if (formula) {
      return formula;
    }
  }
  return null;
}
function homebrewCellarRoots(env) {
  const roots = [];
  const explicitCellar = normalizePathRoot(env.HOMEBREW_CELLAR);
  if (explicitCellar) {
    roots.push(explicitCellar);
  }
  const prefixes = [
    env.HOMEBREW_PREFIX,
    "/opt/homebrew",
    "/usr/local",
    "/home/linuxbrew/.linuxbrew"
  ];
  for (const prefix of prefixes) {
    const normalized = normalizePathRoot(prefix);
    if (normalized) {
      roots.push(`${normalized}/Cellar`);
    }
  }
  return [...new Set(roots)];
}
function isKnownPnpmGlobalStore(path, env) {
  return pnpmGlobalStoreRoots(env).some((root) => {
    if (!isPathInsideRoot(path, root)) {
      return false;
    }
    const relative = path.slice(root.length).replace(/^\/+/, "");
    return /^\d+\/\.pnpm\//.test(relative);
  });
}
function pnpmGlobalStoreRoots(env) {
  const roots = [];
  const home2 = normalizePathRoot(env.HOME ?? env.USERPROFILE);
  if (home2) {
    roots.push(`${home2}/Library/pnpm/global`);
    roots.push(`${home2}/.local/share/pnpm/global`);
    roots.push(`${home2}/AppData/Local/pnpm/global`);
  }
  const localAppData = normalizePathRoot(env.LOCALAPPDATA);
  if (localAppData) {
    roots.push(`${localAppData}/pnpm/global`);
  }
  return [...new Set(roots)];
}
function isKnownNpmGlobalInstall(path, env) {
  return npmGlobalNodeModulesRoots(env).some((root) => isPathInsideRoot(path, root)) || isKnownVersionManagerNpmGlobal(path, env);
}
function npmGlobalNodeModulesRoots(env) {
  const roots = [
    "/usr/local/lib/node_modules",
    "/usr/lib/node_modules",
    "/opt/homebrew/lib/node_modules",
    "/opt/local/lib/node_modules"
  ];
  const prefixes = [env.npm_config_prefix, env.NPM_CONFIG_PREFIX];
  for (const prefix of prefixes) {
    const normalized = normalizePathRoot(prefix);
    if (normalized) {
      roots.push(`${normalized}/lib/node_modules`, `${normalized}/node_modules`);
    }
  }
  const appData = normalizePathRoot(env.APPDATA);
  if (appData) {
    roots.push(`${appData}/npm/node_modules`);
  }
  const home2 = normalizePathRoot(env.HOME ?? env.USERPROFILE);
  if (home2) {
    roots.push(`${home2}/.npm-global/lib/node_modules`, `${home2}/.npm-packages/lib/node_modules`);
  }
  return [...new Set(roots)];
}
function isKnownVersionManagerNpmGlobal(path, env) {
  return versionManagerNodeRoots(env).some((root) => isPathInsideRoot(path, root) && path.includes("/lib/node_modules/"));
}
function versionManagerNodeRoots(env) {
  const roots = [];
  const home2 = normalizePathRoot(env.HOME ?? env.USERPROFILE);
  if (home2) {
    roots.push(`${home2}/.nvm/versions/node`, `${home2}/.local/share/fnm/node-versions`, `${home2}/.asdf/installs/nodejs`, `${home2}/.nodenv/versions`, `${home2}/.local/share/mise/installs/node`, `${home2}/.volta/tools/image/node`);
  }
  const nvmDir = normalizePathRoot(env.NVM_DIR);
  if (nvmDir) {
    roots.push(`${nvmDir}/versions/node`);
  }
  const fnmDir = normalizePathRoot(env.FNM_DIR);
  if (fnmDir) {
    roots.push(`${fnmDir}/node-versions`);
  }
  return [...new Set(roots)];
}
function planUpgrade(method, packageName) {
  switch (method.kind) {
    case "npm-global":
      return {
        method: method.kind,
        command: `npm install -g ${packageName}@latest`,
        argv: ["npm", "install", "-g", `${packageName}@latest`]
      };
    case "pnpm-global":
      return {
        method: method.kind,
        command: `pnpm add -g ${packageName}@latest`,
        argv: ["pnpm", "add", "-g", `${packageName}@latest`]
      };
    case "homebrew":
      if (method.formula) {
        return {
          method: method.kind,
          command: `brew upgrade ${method.formula}`,
          argv: ["brew", "upgrade", method.formula]
        };
      }
      return {
        method: method.kind,
        command: `brew upgrade ${packageName}`,
        argv: null,
        note: "Could not determine the Homebrew formula automatically"
      };
    case "npx":
      return {
        method: method.kind,
        command: `npx -y ${packageName}@latest`,
        argv: null,
        note: "npx always runs the latest published version, so no install is needed"
      };
    case "unknown":
      return {
        method: method.kind,
        command: `npm install -g ${packageName}@latest`,
        argv: null,
        note: "Could not determine how this tool was installed"
      };
  }
}
function packageManagerExecutable(command, platform) {
  if (platform === "win32" && (command === "npm" || command === "pnpm" || command === "npx")) {
    return `${command}.cmd`;
  }
  return command;
}
function shouldUseWindowsPackageManagerShell(command, platform) {
  return platform === "win32" && (command === "npm" || command === "pnpm" || command === "npx");
}
async function npmViewVersion(packageName, platform = process.platform) {
  try {
    const command = packageManagerExecutable("npm", platform);
    const { stdout } = await execFileAsync(command, ["view", packageName, "version"], {
      timeout: 2e4,
      shell: shouldUseWindowsPackageManagerShell("npm", platform)
    });
    const version = stdout.trim();
    return version.length > 0 ? version : null;
  } catch {
    return null;
  }
}
function registryPath(packageName) {
  return packageName.startsWith("@") ? packageName.replace("/", "%2f") : packageName;
}
function notPublishedError(packageName) {
  return new AxiError(`${packageName} is not published to the npm registry`, "UPDATE_ERROR", [
    "Confirm the package name is correct",
    `Run \`npm view ${packageName} version\` to check manually`
  ]);
}
var RegistryNotFoundError = class extends Error {
};
async function withRegistryTimeout(timeoutMs, operation) {
  const controller = new AbortController();
  let timer;
  const timeout = new Promise((_resolve, reject) => {
    timer = setTimeout(() => {
      controller.abort();
      reject(new Error(`Registry fetch timed out after ${timeoutMs}ms`));
    }, timeoutMs);
    timer.unref?.();
  });
  try {
    return await Promise.race([operation(controller.signal), timeout]);
  } finally {
    if (timer) {
      clearTimeout(timer);
    }
  }
}
async function fetchRegistryVersion(fetchImpl, packageName, timeoutMs) {
  return withRegistryTimeout(timeoutMs, async (signal) => {
    const response = await fetchImpl(`${REGISTRY_BASE}/${registryPath(packageName)}/latest`, { headers: { accept: "application/json" }, signal });
    if (response.ok) {
      const data = await response.json();
      if (typeof data.version === "string" && data.version.length > 0) {
        return data.version;
      }
    } else if (response.status === 404) {
      throw new RegistryNotFoundError();
    }
    return null;
  });
}
async function fetchLatestVersion(packageName, options = {}) {
  const fetchImpl = options.fetchImpl === void 0 ? globalThis.fetch : options.fetchImpl ?? void 0;
  let registryNotFound = false;
  if (typeof fetchImpl === "function") {
    try {
      const version = await fetchRegistryVersion(fetchImpl, packageName, options.fetchTimeoutMs ?? REGISTRY_FETCH_TIMEOUT_MS);
      if (version) {
        return version;
      }
    } catch (error) {
      if (error instanceof RegistryNotFoundError) {
        registryNotFound = true;
      } else if (error instanceof AxiError) {
        throw error;
      }
    }
  }
  const viewed = await (options.npmView ?? ((name) => npmViewVersion(name, options.platform)))(packageName);
  if (viewed) {
    return viewed;
  }
  if (registryNotFound) {
    throw notPublishedError(packageName);
  }
  throw new AxiError(`Could not reach the npm registry to check for updates to ${packageName}`, "UPDATE_ERROR", [
    "Check your network connection and try again",
    `Run \`npm view ${packageName} version\` to check manually`
  ]);
}
async function defaultRunInstall(plan, stdout, context) {
  const argv = plan.argv;
  if (!argv || argv.length === 0) {
    return { ok: false, message: "No runnable upgrade command" };
  }
  stdout.write(`running: ${plan.command}
`);
  return new Promise((resolve3) => {
    const [command, ...args] = argv;
    const child = spawn(packageManagerExecutable(command, context.platform), args, {
      stdio: ["ignore", "pipe", "pipe"],
      shell: shouldUseWindowsPackageManagerShell(command, context.platform)
    });
    child.stdout?.on("data", (chunk) => {
      process.stderr.write(chunk);
    });
    child.stderr?.on("data", (chunk) => {
      process.stderr.write(chunk);
    });
    child.on("error", (error) => {
      resolve3({ ok: false, message: error.message });
    });
    child.on("close", (code) => {
      resolve3(code === 0 ? { ok: true } : { ok: false, message: `${plan.command} exited with code ${code}` });
    });
  });
}
function binNameFromArgv(invokedAs) {
  return basename(invokedAs ?? "tool") || "tool";
}
function resolveEntry(invokedAs, realpath) {
  if (!invokedAs) {
    return void 0;
  }
  try {
    return realpath(invokedAs);
  } catch {
    return invokedAs;
  }
}
function resolveInstalledVersion(invokedAs, realpath, fs) {
  const installedEntry = resolveEntry(invokedAs, realpath);
  return installedEntry ? readNearestPackageJson(installedEntry, fs).version : void 0;
}
function homebrewUpgradeOutput(options) {
  const update = {
    package: options.packageName,
    previous: options.current,
    latest: options.latest
  };
  if (options.installedVersion) {
    update.installed = options.installedVersion;
    update.available = isUpdateAvailable(options.installedVersion, options.latest);
  } else {
    update.action = "upgrade-command-ran";
    update.result = "installed version unknown";
  }
  return {
    update,
    command: options.command
  };
}
function parseUpdateArgs(args, binName) {
  if (args.length === 0) {
    return "install";
  }
  if (args.length === 1 && (args[0] === "--check" || args[0] === "--dry-run")) {
    return "check";
  }
  const unknown = args.find((arg) => arg !== "--check" && arg !== "--dry-run");
  throw new AxiError(unknown ? `Unknown update option: ${unknown}` : "Invalid update arguments", "VALIDATION_ERROR", [
    `Run \`${binName} update --help\``,
    `Use \`${binName} update --check\` to check without installing`
  ]);
}
async function runUpdate(options) {
  const invokedAs = options.invokedAs ?? process.argv[1];
  const binName = binNameFromArgv(invokedAs);
  const mode = parseUpdateArgs(options.args, binName);
  const platform = options.platform ?? process.platform;
  const realpath = options.realpath ?? ((path) => realpathSync(path));
  const entry = resolveEntry(invokedAs, realpath);
  const fs = options.fs ?? nodeFs;
  const fromPackageJson = entry ? readNearestPackageJson(entry, fs) : {};
  const packageName = options.packageName ?? fromPackageJson.packageName;
  const current = options.version ?? fromPackageJson.version;
  if (!packageName) {
    throw new AxiError("Could not determine the package name to update", "UPDATE_ERROR", [
      "Reinstall the tool from npm so its package.json is available",
      "Tool authors can pass `packageName` to runAxiCli()"
    ]);
  }
  if (!current) {
    throw new AxiError(`Could not determine the current version of ${packageName}`, "UPDATE_ERROR", [
      "Reinstall the tool from npm so its version is available",
      "Tool authors can pass `version` to runAxiCli()"
    ]);
  }
  const fetchLatest = options.fetchLatest ?? ((name) => fetchLatestVersion(name, { platform }));
  const latest = await fetchLatest(packageName);
  const available = isUpdateAvailable(current, latest);
  if (mode === "check") {
    const output = {
      update: { package: packageName, current, latest, available }
    };
    if (available) {
      output.help = [`Run \`${binName} update\` to upgrade`];
    }
    return output;
  }
  if (!available) {
    return {
      update: `${packageName} is already on the latest version (${current})`
    };
  }
  const method = entry ? detectInstallMethod({ entry, env: options.env }) : { kind: "unknown" };
  const plan = planUpgrade(method, packageName);
  if (!plan.argv) {
    const help = method.kind === "npx" ? `Re-run with \`${plan.command}\` to use the latest version` : `Run \`${plan.command}\` to upgrade`;
    return {
      update: {
        package: packageName,
        current,
        latest,
        available: true,
        action: "manual",
        ...plan.note ? { reason: plan.note } : {},
        run: plan.command
      },
      help: [help]
    };
  }
  const runInstall = options.runInstall ?? defaultRunInstall;
  const result = await runInstall(plan, options.stdout, { platform });
  if (!result.ok) {
    throw new AxiError(`Failed to upgrade ${packageName}`, "UPDATE_ERROR", [
      `Run \`${plan.command}\` manually`,
      ...result.message ? [result.message] : []
    ]);
  }
  if (method.kind === "homebrew") {
    return homebrewUpgradeOutput({
      packageName,
      current,
      latest,
      installedVersion: resolveInstalledVersion(invokedAs, realpath, fs),
      command: plan.command
    });
  }
  return {
    update: `${packageName} upgraded ${current} -> ${latest}`,
    command: plan.command
  };
}

// node_modules/axi-sdk-js/dist/cli.js
var stdoutWithErrorHandler = /* @__PURE__ */ new WeakSet();
function defaultFormatError(error) {
  if (error instanceof AxiError) {
    return {
      output: `${renderError(error.message, error.code, error.suggestions)}
`,
      exitCode: exitCodeForError(error)
    };
  }
  const message = error instanceof Error ? error.message : String(error);
  return {
    output: `${renderError(message, "UNKNOWN")}
`,
    exitCode: 1
  };
}
function defaultUnknownCommand(command) {
  return `${renderError(`Unknown command: ${command}`, "VALIDATION_ERROR", [
    "Run `--help` to see available commands"
  ])}
`;
}
async function runAxiCli(options) {
  const stdout = options.stdout ?? process.stdout;
  handleStdoutErrors(stdout);
  try {
    await options.initialize?.();
  } catch (error) {
    writeFormattedError(error, stdout, options);
    return;
  }
  const argv = options.argv ?? process.argv.slice(2);
  if (argv.length === 1 && argv[0] === "--help") {
    stdout.write(options.topLevelHelp);
    if (!options.commands.update) {
      if (options.topLevelHelp.length > 0 && !options.topLevelHelp.endsWith("\n")) {
        stdout.write("\n");
      }
      stdout.write(builtinCommandsHelp());
    }
    return;
  }
  if (argv.length === 1 && isVersionFlag(argv[0])) {
    if (!options.version) {
      stdout.write(`${renderError("Version is not configured for this tool", "VALIDATION_ERROR")}
`);
      process.exitCode = 2;
      return;
    }
    stdout.write(`${options.version}
`);
    return;
  }
  const command = argv[0];
  if (!command) {
    await runHandler(options.home, [], { command: void 0, args: [] }, stdout, options, true);
    return;
  }
  if (command.startsWith("-")) {
    stdout.write(renderLeadingFlagError(command));
    process.exitCode = 2;
    return;
  }
  const args = argv.slice(1);
  if (command === "update" && !options.commands.update) {
    await runBuiltinUpdate(args, stdout, options);
    return;
  }
  if (args.includes("--help")) {
    const help = options.getCommandHelp?.(command);
    if (help) {
      stdout.write(help);
      return;
    }
  }
  const handler = options.commands[command];
  if (!handler) {
    stdout.write((options.renderUnknownCommand ?? defaultUnknownCommand)(command));
    process.exitCode = 2;
    return;
  }
  await runHandler(handler, args, { command, args }, stdout, options, false);
}
function handleStdoutErrors(stdout) {
  const errorObservable = stdout;
  if (typeof errorObservable.on !== "function" || stdoutWithErrorHandler.has(stdout)) {
    return;
  }
  stdoutWithErrorHandler.add(stdout);
  errorObservable.on("error", (error) => {
    if (typeof error === "object" && error !== null && "code" in error && error.code === "EPIPE") {
      process.exitCode = 0;
      return;
    }
    throw error;
  });
}
async function runHandler(handler, args, contextInput, stdout, options, isHomeView) {
  try {
    const context = await options.resolveContext?.(contextInput);
    const output = await handler(args, context);
    stdout.write(`${renderCommandOutput(output, options, isHomeView)}
`);
  } catch (error) {
    writeFormattedError(error, stdout, options);
  }
}
async function runBuiltinUpdate(args, stdout, options) {
  if (args.length === 1 && args[0] === "--help") {
    stdout.write(builtinUpdateHelp());
    return;
  }
  try {
    const output = await runUpdate({
      args,
      stdout,
      packageName: options.packageName,
      version: options.version
    });
    stdout.write(`${renderOutput(output)}
`);
  } catch (error) {
    writeFormattedError(error, stdout, options);
  }
}
function writeFormattedError(error, stdout, options) {
  const formatted = (options.formatError ?? defaultFormatError)(error);
  stdout.write(formatted.output);
  process.exitCode = formatted.exitCode;
}
function resolveBinName() {
  return basename2(process.argv[1] ?? "tool") || "tool";
}
function builtinCommandsHelp() {
  const bin = resolveBinName();
  return `${renderOutput({
    "built-in": {
      update: `Upgrade \`${bin}\` to the latest published version`,
      "update --check": "Report current vs latest without installing"
    }
  })}
`;
}
function builtinUpdateHelp() {
  const bin = resolveBinName();
  return `${renderOutput({
    command: "update",
    description: `Upgrade \`${bin}\` to the latest published npm version`,
    flags: {
      "--check": "Report current vs latest and exit without installing"
    },
    examples: [`${bin} update`, `${bin} update --check`]
  })}
`;
}
function renderLeadingFlagError(flag2) {
  const bin = basename2(process.argv[1] ?? "tool") || "tool";
  return `${renderError("Flags must come after the command", "VALIDATION_ERROR", [
    `Run \`${bin} <command> [args] [flags]\``,
    `Move \`${flag2}\` after the command instead of before it`
  ])}
`;
}
function isVersionFlag(flag2) {
  return flag2 === "-v" || flag2 === "-V" || flag2 === "--version";
}
function renderCommandOutput(output, options, isHomeView) {
  if (!isHomeView) {
    return renderOutput(output);
  }
  const header = homeHeaderOutput({ description: options.description });
  if (typeof output === "string") {
    return `${renderOutput(header)}
${output}`;
  }
  return renderOutput(mergeHomeHeader(header, output));
}
function mergeHomeHeader(header, output) {
  const rest = { ...output };
  delete rest.bin;
  delete rest.description;
  return {
    ...header,
    ...rest
  };
}

// node_modules/axi-sdk-js/dist/hooks.js
import { existsSync as existsSync2, mkdirSync, readFileSync as readFileSync2, realpathSync as realpathSync2, rmSync, statSync, writeFileSync } from "node:fs";
import { homedir as homedir2 } from "node:os";
import { basename as basename3, delimiter, dirname as dirname2, join as join2, resolve } from "node:path";
var OPENCODE_PLUGIN_MANAGED_PREFIX = "axi-sdk-js managed opencode plugin:";
function isManagedHook(hook2, marker) {
  return typeof hook2?.command === "string" && hook2.command.includes(marker);
}
function computeSessionStartHookUpdate(settings, spec) {
  const updated = structuredClone(settings);
  let changed = false;
  if (!updated.hooks) {
    updated.hooks = {};
    changed = true;
  }
  if (Array.isArray(updated.hooks.session_start)) {
    const legacyHooks = updated.hooks.session_start.filter((hook2) => !isManagedHook(hook2, spec.marker));
    if (legacyHooks.length !== updated.hooks.session_start.length) {
      changed = true;
      if (legacyHooks.length === 0) {
        delete updated.hooks.session_start;
      } else {
        updated.hooks.session_start = legacyHooks;
      }
    }
  }
  if (!Array.isArray(updated.hooks.SessionStart)) {
    updated.hooks.SessionStart = [];
    changed = true;
  }
  for (const group2 of updated.hooks.SessionStart) {
    if (!Array.isArray(group2.hooks)) {
      continue;
    }
    for (const hook2 of group2.hooks) {
      if (!isManagedHook(hook2, spec.marker)) {
        continue;
      }
      const timeout = spec.timeoutSeconds ?? 10;
      const isCorrect = hook2.command === spec.command && hook2.type === "command" && hook2.timeout === timeout;
      if (isCorrect && !changed) {
        return [settings, false];
      }
      hook2.command = spec.command;
      hook2.type = "command";
      hook2.timeout = timeout;
      return [updated, true];
    }
  }
  updated.hooks.SessionStart.push({
    matcher: "",
    hooks: [
      {
        type: "command",
        command: spec.command,
        timeout: spec.timeoutSeconds ?? 10
      }
    ]
  });
  return [updated, true];
}
function computeSessionStartHookRemoval(settings, marker) {
  if (!settings.hooks) {
    return [settings, false];
  }
  const updated = structuredClone(settings);
  const hooks = updated.hooks;
  if (!hooks) {
    return [settings, false];
  }
  let changed = false;
  if (Array.isArray(hooks.session_start)) {
    const remaining = hooks.session_start.filter((hook2) => !isManagedHook(hook2, marker));
    if (remaining.length !== hooks.session_start.length) {
      changed = true;
      if (remaining.length === 0) {
        delete hooks.session_start;
      } else {
        hooks.session_start = remaining;
      }
    }
  }
  if (Array.isArray(hooks.SessionStart)) {
    const remainingGroups = [];
    let sessionStartChanged = false;
    for (const group2 of hooks.SessionStart) {
      if (!Array.isArray(group2.hooks)) {
        remainingGroups.push(group2);
        continue;
      }
      const remainingHooks = group2.hooks.filter((hook2) => !isManagedHook(hook2, marker));
      if (remainingHooks.length === group2.hooks.length) {
        remainingGroups.push(group2);
        continue;
      }
      sessionStartChanged = true;
      if (remainingHooks.length > 0) {
        remainingGroups.push({ ...group2, hooks: remainingHooks });
      }
    }
    if (sessionStartChanged) {
      changed = true;
      if (remainingGroups.length > 0) {
        hooks.SessionStart = remainingGroups;
      } else {
        delete hooks.SessionStart;
      }
    }
  }
  if (Object.keys(hooks).length === 0) {
    delete updated.hooks;
  }
  return changed ? [updated, true] : [settings, false];
}
function computeCodexConfigUpdate(content) {
  const newline = content.includes("\r\n") ? "\r\n" : "\n";
  const normalized = content.length === 0 ? "" : content;
  if (normalized.trim().length === 0) {
    return [`[features]${newline}hooks = true${newline}`, true];
  }
  const lines = normalized.split(/\r?\n/);
  const updated = [...lines];
  let inFeatures = false;
  let sawFeatures = false;
  for (let index = 0; index < updated.length; index++) {
    const line = updated[index];
    const section = line.match(/^\s*(\[{1,2})([^\]]+)(\]{1,2})\s*(?:#.*)?$/);
    if (section) {
      const isTableHeader = section[1] === "[" && section[3] === "]" || section[1] === "[[" && section[3] === "]]";
      if (!isTableHeader) {
        continue;
      }
      const sectionName = section[2].trim();
      if (inFeatures) {
        updated.splice(index, 0, "hooks = true");
        return [updated.join(newline), true];
      }
      inFeatures = sectionName === "features";
      sawFeatures ||= inFeatures;
      continue;
    }
    if (!inFeatures) {
      continue;
    }
    const flag2 = line.match(/^\s*hooks\s*=\s*(true|false)\s*(?:#.*)?$/);
    if (!flag2) {
      continue;
    }
    if (flag2[1] === "true") {
      return [content, false];
    }
    updated[index] = line.replace(/false/, "true");
    return [updated.join(newline), true];
  }
  if (sawFeatures) {
    const suffix = normalized.endsWith(newline) ? "" : newline;
    return [`${normalized}${suffix}hooks = true${newline}`, true];
  }
  const separator = normalized.endsWith(newline) ? newline : `${newline}${newline}`;
  return [
    `${normalized}${separator}[features]${newline}hooks = true${newline}`,
    true
  ];
}
function sanitizeOpenCodePluginFilePart(marker) {
  return marker.replace(/[^A-Za-z0-9._-]+/g, "_");
}
function sanitizeOpenCodeExportName(marker) {
  const name = marker.split(/[^A-Za-z0-9]+/).filter(Boolean).map((part) => `${part[0]?.toUpperCase() ?? ""}${part.slice(1)}`).join("");
  return `Axi${name || "Plugin"}AmbientContextPlugin`;
}
function buildOpenCodeAmbientPluginSource(marker, command, timeoutSeconds) {
  const exportName = sanitizeOpenCodeExportName(marker);
  const managedMarker = `${OPENCODE_PLUGIN_MANAGED_PREFIX} ${marker}`;
  return `// ${managedMarker}
// This file is generated by axi-sdk-js. It is safe to edit only if you remove the managed marker above.
import { spawn } from "node:child_process";

const command = ${JSON.stringify(command)};
const marker = ${JSON.stringify(marker)};
const ambientHeader = ${JSON.stringify(`## AXI ambient context: ${marker}`)};
const timeoutMs = ${JSON.stringify(timeoutSeconds * 1e3)};

function runAxiHomeView(cwd) {
  return new Promise((resolve) => {
    const child = spawn(command, [], {
      cwd: directoryOrFallback(cwd),
      env: process.env,
      shell: false,
      stdio: ["ignore", "pipe", "pipe"],
    });

    let stdout = "";
    let stderr = "";
    let settled = false;

    const timer = setTimeout(() => {
      if (settled) return;
      settled = true;
      child.kill("SIGTERM");
      resolve("error: " + marker + " ambient context timed out after " + timeoutMs + "ms");
    }, timeoutMs);

    child.stdout?.setEncoding("utf-8");
    child.stderr?.setEncoding("utf-8");
    child.stdout?.on("data", (chunk) => {
      stdout += chunk;
    });
    child.stderr?.on("data", (chunk) => {
      stderr += chunk;
    });
    child.on("error", (error) => {
      if (settled) return;
      settled = true;
      clearTimeout(timer);
      resolve("error: " + marker + " ambient context failed: " + error.message);
    });
    child.on("close", (code) => {
      if (settled) return;
      settled = true;
      clearTimeout(timer);
      if (code === 0) {
        resolve(stdout.trim());
        return;
      }
      const message = (stderr || stdout || marker + " exited with code " + code).trim();
      resolve("error: " + marker + " ambient context failed: " + message);
    });
  });
}

function directoryOrFallback(directory) {
  return typeof directory === "string" && directory.length > 0
    ? directory
    : process.cwd();
}

export const ${exportName} = async ({ directory }) => {
  const sessionCache = new Map();

  return {
    "experimental.chat.system.transform": async (input, output) => {
      const sessionID = input.sessionID ?? "__global__";
      let homeView = sessionCache.get(sessionID);
      if (homeView === undefined) {
        homeView = await runAxiHomeView(directory);
        sessionCache.set(sessionID, homeView);
      }

      if (homeView.length === 0) return;
      output.system.push(ambientHeader + "\\n" + homeView);
    },
  };
};
`;
}
function openCodePluginFileName(marker) {
  return `axi-${sanitizeOpenCodePluginFilePart(marker)}.js`;
}
function openCodePluginDir(scope, home2, root) {
  return scope === "project" ? join2(root, ".opencode", "plugins") : join2(home2, ".config", "opencode", "plugins");
}
function resolveHookScopeTargets(marker, options) {
  const home2 = options.homeDir ?? homedir2();
  const scope = options.scope ?? "user";
  const root = scope === "project" ? resolve(options.projectDir ?? process.cwd()) : home2;
  return {
    scope,
    home: home2,
    root,
    claudeSettingsPath: join2(root, ".claude", "settings.json"),
    codexHooksPath: join2(root, ".codex", "hooks.json"),
    codexConfigPath: join2(home2, ".codex", "config.toml"),
    openCodePluginPath: join2(openCodePluginDir(scope, home2, root), openCodePluginFileName(marker))
  };
}
function installOpenCodeAmbientPlugin(pluginPath, marker, command, timeoutSeconds, onError) {
  const managedMarker = `${OPENCODE_PLUGIN_MANAGED_PREFIX} ${marker}`;
  const next = buildOpenCodeAmbientPluginSource(marker, command, timeoutSeconds);
  try {
    mkdirSync(dirname2(pluginPath), { recursive: true });
    const current = existsSync2(pluginPath) ? readFileSync2(pluginPath, "utf-8") : void 0;
    if (current !== void 0 && !current.includes(managedMarker)) {
      onError?.(`${pluginPath}: refusing to overwrite unmanaged OpenCode plugin`);
      return;
    }
    if (current !== next) {
      writeFileSync(pluginPath, next, "utf-8");
    }
  } catch (error) {
    const message = error instanceof Error ? error.message : String(error);
    onError?.(`${pluginPath}: ${message}`);
  }
}
function resolvePortableHookCommand(execPath, binaryNames, marker, context) {
  if (binaryNames.length === 0) {
    return execPath;
  }
  const resolvedExec = context.resolveRealPath(execPath);
  if (!resolvedExec) {
    return execPath;
  }
  for (const name of binaryNames) {
    if (!name.includes(marker)) {
      continue;
    }
    for (const dir of context.pathEntries) {
      if (!dir)
        continue;
      for (const ext of context.pathExtensions) {
        const candidate = join2(dir, `${name}${ext}`);
        const resolvedCandidate = context.resolveRealPath(candidate);
        if (resolvedCandidate && resolvedCandidate === resolvedExec) {
          return name;
        }
        const shimTarget = context.resolveShimTarget?.(candidate);
        if (shimTarget && shimTarget === resolvedExec) {
          return name;
        }
      }
    }
  }
  return execPath;
}
var NPM_SHIM_SCRIPT_PATTERNS = [
  // Git Bash / POSIX shim: exec node "$basedir/node_modules/<pkg>/.../cli.js"
  /"\$basedir\/([^"]+\.[cm]?js)"/,
  // Windows .cmd shim: "%dp0%\node_modules\<pkg>\...\cli.js"
  /%~?dp0%?[\\/]([^"\r\n]+\.[cm]?js)/i
];
function extractNpmShimScriptPath(content) {
  for (const pattern of NPM_SHIM_SCRIPT_PATTERNS) {
    const match = content.match(pattern);
    if (match?.[1]) {
      return match[1];
    }
  }
  return void 0;
}
function buildDefaultPortableCommandContext() {
  const rawPath = process.env.PATH ?? process.env.Path ?? "";
  const pathEntries = rawPath.split(delimiter).filter(Boolean);
  const pathExtensions = process.platform === "win32" ? (
    // Git Bash resolves the extensionless shim, which PATHEXT omits.
    ["", ...(process.env.PATHEXT ?? ".COM;.EXE;.BAT;.CMD").split(";")]
  ) : [""];
  return {
    pathEntries,
    pathExtensions,
    resolveRealPath: (absolutePath) => {
      try {
        const stat = statSync(absolutePath);
        if (!stat.isFile()) {
          return void 0;
        }
        return realpathSync2(absolutePath);
      } catch {
        return void 0;
      }
    },
    resolveShimTarget: (shimPath) => {
      try {
        const relative = extractNpmShimScriptPath(readFileSync2(shimPath, "utf-8"));
        if (!relative) {
          return void 0;
        }
        return realpathSync2(resolve(dirname2(shimPath), relative));
      } catch {
        return void 0;
      }
    }
  };
}
function shouldInstallHooksForNodeAxiExecPath(execPath, policy) {
  const normalized = resolve(execPath).replaceAll("\\", "/");
  if (!normalized.includes(policy.marker) || normalized.endsWith(".ts")) {
    return false;
  }
  const fileName = basename3(normalized);
  if (policy.binaryNames?.includes(fileName)) {
    return true;
  }
  return policy.distEntrypoints?.some((entrypoint) => normalized.endsWith(entrypoint.replaceAll("\\", "/"))) ?? false;
}
function inferHookOptions(execPath) {
  if (!execPath) {
    return void 0;
  }
  const normalized = execPath.replaceAll("\\", "/");
  const match = normalized.match(/(?:^|\/)dist\/bin\/([^/]+)\.js$/);
  if (match?.[1]) {
    const marker = match[1];
    return {
      execPath,
      marker,
      binaryNames: [marker],
      distEntrypoints: [`dist/bin/${marker}.js`]
    };
  }
  const fileName = normalized.split("/").pop() ?? "";
  if (!fileName || fileName.includes(".") || fileName === "node") {
    return void 0;
  }
  return {
    execPath,
    marker: fileName,
    binaryNames: [fileName],
    distEntrypoints: [`dist/bin/${fileName}.js`]
  };
}
function buildInferredHookInstallPolicy(marker, options, inferred) {
  const binaryNames = options.binaryNames ?? inferred.binaryNames;
  const distEntrypoints = options.distEntrypoints ?? inferred.distEntrypoints;
  return (execPath) => shouldInstallHooksForNodeAxiExecPath(execPath, {
    marker,
    binaryNames,
    distEntrypoints
  });
}
function installSessionStartHooks(options = {}) {
  const inferred = inferHookOptions(options.execPath ?? process.argv[1]);
  const marker = options.marker ?? inferred?.marker;
  if (!marker) {
    return;
  }
  const execPath = resolve(options.execPath ?? inferred?.execPath ?? process.argv[1] ?? "");
  if (!execPath) {
    return;
  }
  const defaultPolicyOptions = inferred ?? {
    execPath,
    marker,
    binaryNames: [marker],
    distEntrypoints: [`dist/bin/${marker}.js`]
  };
  const shouldInstall = options.shouldInstall ?? buildInferredHookInstallPolicy(marker, options, defaultPolicyOptions);
  if (shouldInstall && !shouldInstall(execPath)) {
    return;
  }
  const binaryNames = options.binaryNames ?? inferred?.binaryNames ?? [];
  const command = resolvePortableHookCommand(execPath, binaryNames, marker, buildDefaultPortableCommandContext());
  const targets = resolveHookScopeTargets(marker, options);
  const jsonTargets = [targets.claudeSettingsPath, targets.codexHooksPath];
  const codexConfigPath = targets.codexConfigPath;
  installOpenCodeAmbientPlugin(targets.openCodePluginPath, marker, command, options.timeoutSeconds ?? 10, options.onError);
  for (const target of jsonTargets) {
    try {
      mkdirSync(dirname2(target), { recursive: true });
      const current = existsSync2(target) ? JSON.parse(readFileSync2(target, "utf-8")) : {};
      const [updated, changed] = computeSessionStartHookUpdate(current, {
        marker,
        command,
        timeoutSeconds: options.timeoutSeconds
      });
      if (changed) {
        writeFileSync(target, `${JSON.stringify(updated, null, 2)}
`, "utf-8");
      }
    } catch (error) {
      const message = error instanceof Error ? error.message : String(error);
      options.onError?.(`${target}: ${message}`);
    }
  }
  try {
    mkdirSync(dirname2(codexConfigPath), { recursive: true });
    const current = existsSync2(codexConfigPath) ? readFileSync2(codexConfigPath, "utf-8") : "";
    const [updated, changed] = computeCodexConfigUpdate(current);
    if (changed) {
      writeFileSync(codexConfigPath, updated, "utf-8");
    }
  } catch (error) {
    const message = error instanceof Error ? error.message : String(error);
    options.onError?.(`${codexConfigPath}: ${message}`);
  }
}
function resolveStatusMarker(options, callerName) {
  const inferred = inferHookOptions(options.execPath ?? process.argv[1]);
  const marker = options.marker ?? inferred?.marker;
  if (!marker) {
    throw new Error(`${callerName}: unable to infer a hook marker from the current process; pass { marker } explicitly`);
  }
  return marker;
}
function hasManagedJsonHookEntry(path, marker) {
  if (!existsSync2(path)) {
    return false;
  }
  try {
    const settings = JSON.parse(readFileSync2(path, "utf-8"));
    const groups = settings.hooks?.SessionStart ?? [];
    const inGroups = groups.some((group2) => (group2.hooks ?? []).some((hook2) => isManagedHook(hook2, marker)));
    const legacy = settings.hooks?.session_start ?? [];
    return inGroups || legacy.some((hook2) => isManagedHook(hook2, marker));
  } catch {
    return false;
  }
}
function hasManagedOpenCodePlugin(path, marker) {
  if (!existsSync2(path)) {
    return false;
  }
  try {
    return readFileSync2(path, "utf-8").includes(`${OPENCODE_PLUGIN_MANAGED_PREFIX} ${marker}`);
  } catch {
    return false;
  }
}
function isCodexHooksFeatureEnabled(path) {
  if (!existsSync2(path)) {
    return false;
  }
  try {
    const [, changed] = computeCodexConfigUpdate(readFileSync2(path, "utf-8"));
    return !changed;
  } catch {
    return false;
  }
}
function sessionStartHookStatus(options = {}) {
  const marker = resolveStatusMarker(options, "sessionStartHookStatus");
  const targets = resolveHookScopeTargets(marker, options);
  return {
    marker,
    scope: targets.scope,
    claude: {
      installed: hasManagedJsonHookEntry(targets.claudeSettingsPath, marker),
      path: targets.claudeSettingsPath
    },
    codex: {
      installed: hasManagedJsonHookEntry(targets.codexHooksPath, marker),
      path: targets.codexHooksPath,
      userFeatureEnabled: isCodexHooksFeatureEnabled(targets.codexConfigPath),
      userFeaturePath: targets.codexConfigPath
    },
    opencode: {
      installed: hasManagedOpenCodePlugin(targets.openCodePluginPath, marker),
      path: targets.openCodePluginPath
    }
  };
}
function uninstallSessionStartHooks(options = {}) {
  const inferred = inferHookOptions(options.execPath ?? process.argv[1]);
  const marker = options.marker ?? inferred?.marker;
  if (!marker) {
    return;
  }
  const targets = resolveHookScopeTargets(marker, options);
  for (const target of [targets.claudeSettingsPath, targets.codexHooksPath]) {
    try {
      if (!existsSync2(target)) {
        continue;
      }
      const current = JSON.parse(readFileSync2(target, "utf-8"));
      const [updated, changed] = computeSessionStartHookRemoval(current, marker);
      if (changed) {
        writeFileSync(target, `${JSON.stringify(updated, null, 2)}
`, "utf-8");
      }
    } catch (error) {
      const message = error instanceof Error ? error.message : String(error);
      options.onError?.(`${target}: ${message}`);
    }
  }
  const pluginPath = targets.openCodePluginPath;
  try {
    if (existsSync2(pluginPath)) {
      const managedMarker = `${OPENCODE_PLUGIN_MANAGED_PREFIX} ${marker}`;
      if (readFileSync2(pluginPath, "utf-8").includes(managedMarker)) {
        rmSync(pluginPath, { force: true });
      } else {
        options.onError?.(`${pluginPath}: refusing to remove unmanaged OpenCode plugin`);
      }
    }
  } catch (error) {
    const message = error instanceof Error ? error.message : String(error);
    options.onError?.(`${pluginPath}: ${message}`);
  }
}

// src/cli/reference.ts
var DESCRIPTION = "Drive SquadQuest's App Store Connect releases and signing assets \u2014 version, notes, build, review submission, profiles, certs";
var COMMAND_GROUPS = [
  {
    group: "Release",
    commands: [
      {
        usage: "builds [--limit <n>]",
        summary: "Recent TestFlight builds with processing state"
      },
      {
        usage: "version list [--limit <n>]",
        summary: "App Store versions and where each one sits"
      },
      {
        usage: "version create <version>",
        summary: "Start a new App Store version (e.g. 1.47.0)"
      },
      {
        usage: "version show <version>",
        summary: "One version in full: state, build, notes, release type"
      },
      {
        usage: "notes set <version> --file <path> | --text <s> | --from-release <tag>",
        summary: "Set What's New, reusing the GitHub release notes when given a tag"
      },
      {
        usage: "build attach <version> <build>",
        summary: "Bind a processed TestFlight build to a version"
      },
      {
        usage: "submit <version>",
        summary: "Submit for App Store review (asks first)"
      },
      {
        usage: "release <version>",
        summary: "Release a version that is approved and waiting (asks first)"
      }
    ]
  },
  {
    group: "Signing assets",
    commands: [
      {
        usage: "profiles list",
        summary: "Provisioning profiles for both bundle ids, with expiry"
      },
      {
        usage: "profiles regenerate [--bundle-id <id>]",
        summary: "Recreate profiles after expiry or a device change"
      },
      { usage: "certs list", summary: "Signing certificates and when they expire" },
      { usage: "devices list", summary: "Registered devices" },
      {
        usage: "devices add <name> <udid>",
        summary: "Register a device for development builds"
      }
    ]
  },
  {
    group: "Session",
    commands: [
      { usage: "home", summary: "Identity and quick reference (the session-start view)" },
      {
        usage: "hook install|uninstall|status [--global]",
        summary: "Manage the SessionStart hook"
      }
    ]
  }
];

// src/cli/asc.ts
import { createSign, createPrivateKey } from "node:crypto";
import { readFileSync as readFileSync3, readdirSync, existsSync as existsSync3 } from "node:fs";
import { homedir as homedir3 } from "node:os";
import { join as join3 } from "node:path";
var KEY_DIR = join3(homedir3(), ".appstoreconnect", "private_keys");
var APP_BUNDLE_ID = "app.squadquest";
var EXTENSION_BUNDLE_ID = "app.squadquest.ImageNotification";
function loadCredentials() {
  const issuerId = process.env.APPSTORE_ISSUER_ID ?? readIssuerFile();
  if (!issuerId) {
    throw new AxiError(
      "No App Store Connect issuer id found",
      "missing-issuer-id",
      [
        `Set APPSTORE_ISSUER_ID, or write it to ${collapse(join3(KEY_DIR, "issuer_id"))}`,
        "Find it at App Store Connect > Users and Access > Integrations > App Store Connect API"
      ]
    );
  }
  const explicit = process.env.APPSTORE_API_KEY_ID;
  const keyPath = explicit ? join3(KEY_DIR, `AuthKey_${explicit}.p8`) : findSingleKey();
  if (!existsSync3(keyPath)) {
    throw new AxiError(`No API key at ${collapse(keyPath)}`, "missing-api-key", [
      `Download a team key and save it as ${collapse(KEY_DIR)}/AuthKey_<id>.p8`,
      "chmod 600 the file \u2014 it is an account credential"
    ]);
  }
  const keyId = keyPath.replace(/.*AuthKey_/, "").replace(/\.p8$/, "");
  return { issuerId, keyId, privateKey: readFileSync3(keyPath, "utf8") };
}
function readIssuerFile() {
  const path = join3(KEY_DIR, "issuer_id");
  return existsSync3(path) ? readFileSync3(path, "utf8").trim() : void 0;
}
function findSingleKey() {
  let entries = [];
  try {
    entries = readdirSync(KEY_DIR).filter((f) => /^AuthKey_.+\.p8$/.test(f));
  } catch {
    entries = [];
  }
  if (entries.length === 0) {
    return join3(KEY_DIR, "AuthKey_<id>.p8");
  }
  if (entries.length > 1) {
    throw new AxiError(
      `Multiple API keys in ${collapse(KEY_DIR)}`,
      "ambiguous-api-key",
      [
        `Set APPSTORE_API_KEY_ID to pick one: ${entries.map((f) => f.replace(/^AuthKey_|\.p8$/g, "")).join(", ")}`
      ]
    );
  }
  return join3(KEY_DIR, entries[0]);
}
function collapse(p) {
  const home2 = homedir3();
  return home2 && p.startsWith(`${home2}/`) ? `~${p.slice(home2.length)}` : p;
}
function base64url(input) {
  return Buffer.from(input).toString("base64").replace(/\+/g, "-").replace(/\//g, "_").replace(/=+$/, "");
}
function mintToken({ issuerId, keyId, privateKey }) {
  const now = Math.floor(Date.now() / 1e3);
  const header = base64url(JSON.stringify({ alg: "ES256", kid: keyId, typ: "JWT" }));
  const payload = base64url(
    JSON.stringify({ iss: issuerId, iat: now, exp: now + 900, aud: "appstoreconnect-v1" })
  );
  let key;
  try {
    key = createPrivateKey(privateKey);
  } catch {
    throw new AxiError("API key is not a readable private key", "bad-api-key", [
      "Re-download AuthKey_<id>.p8 from App Store Connect (it can only be downloaded once)"
    ]);
  }
  const signer = createSign("SHA256");
  signer.update(`${header}.${payload}`);
  const der = signer.sign({ key, dsaEncoding: "ieee-p1363" });
  return `${header}.${payload}.${base64url(der)}`;
}
var cachedToken;
function token() {
  if (cachedToken && cachedToken.expires > Date.now() + 6e4) return cachedToken.token;
  const t = mintToken(loadCredentials());
  cachedToken = { token: t, expires: Date.now() + 9e5 };
  return t;
}
var BASE = "https://api.appstoreconnect.apple.com";
async function request(method, path, body) {
  const res = await fetch(`${BASE}${path}`, {
    method,
    headers: {
      Authorization: `Bearer ${token()}`,
      ...body ? { "Content-Type": "application/json" } : {}
    },
    ...body ? { body: JSON.stringify(body) } : {}
  });
  const text = await res.text();
  const json = text ? JSON.parse(text) : {};
  if (!res.ok) {
    const detail = json.errors?.[0]?.detail ?? json.errors?.[0]?.title ?? `HTTP ${res.status}`;
    const code = json.errors?.[0]?.code ?? `http-${res.status}`;
    throw new AxiError(detail, String(code).toLowerCase(), suggestFor(res.status));
  }
  return json;
}
function suggestFor(status) {
  if (status === 401) {
    return [
      "The JWT was rejected \u2014 check APPSTORE_ISSUER_ID matches the key's team",
      "Keys are per-team; an individual key won't work here"
    ];
  }
  if (status === 403) {
    return [
      "The key's role is too narrow for this operation",
      "Creating profiles or certificates needs an Admin key; App Manager can only read them"
    ];
  }
  return [];
}
async function requestAll(path) {
  const first = await request("GET", path);
  const data = Array.isArray(first.data) ? [...first.data] : [];
  const included = [...first.included ?? []];
  let next = first.links?.next;
  while (next) {
    const res = await request("GET", next.replace(BASE, ""));
    if (Array.isArray(res.data)) data.push(...res.data);
    if (res.included) included.push(...res.included);
    next = res.links?.next;
  }
  return { data, included };
}
async function getApp() {
  const res = await request(
    "GET",
    `/v1/apps?filter%5BbundleId%5D=${encodeURIComponent(APP_BUNDLE_ID)}&limit=10`
  );
  const apps = (Array.isArray(res.data) ? res.data : []).filter(
    (a) => a.attributes?.bundleId === APP_BUNDLE_ID
  );
  const app = apps[0];
  if (!app) {
    throw new AxiError(`No app found for ${APP_BUNDLE_ID}`, "app-not-found", [
      "Check the API key's team owns this app"
    ]);
  }
  return app;
}

// src/cli/invocation.ts
import { accessSync, constants } from "node:fs";
import { homedir as homedir4 } from "node:os";
import { fileURLToPath } from "node:url";
var cached;
function cliInvocation() {
  if (cached) return cached;
  let bundle;
  try {
    bundle = fileURLToPath(import.meta.url);
  } catch {
    bundle = process.argv[1] ?? "appstore";
  }
  const shim = bundle.replace(/\.mjs$/, "");
  try {
    if (shim !== bundle) {
      accessSync(shim, constants.X_OK);
      cached = quote(collapseHome(shim));
      return cached;
    }
  } catch {
  }
  cached = `node ${quote(collapseHome(bundle))}`;
  return cached;
}
function collapseHome(p) {
  const home2 = homedir4();
  return home2 && p.startsWith(`${home2}/`) ? `~${p.slice(home2.length)}` : p;
}
function quote(p) {
  return /\s/.test(p) ? `"${p}"` : p;
}

// src/cli/commands/signing.ts
var APP_STORE_PROFILE = "IOS_APP_STORE";
var PROFILE_NAMES = {
  [APP_BUNDLE_ID]: "SquadQuest App Store",
  [EXTENSION_BUNDLE_ID]: "SquadQuest ImageNotification App Store"
};
var RELEASE_PROFILE_NAMES = Object.values(PROFILE_NAMES);
function daysUntil(iso) {
  if (!iso) return void 0;
  return Math.round((new Date(iso).getTime() - Date.now()) / 864e5);
}
async function squadquestProfiles() {
  const res = await requestAll("/v1/profiles?limit=200&include=bundleId");
  const bundleIds = new Map(
    (res.included ?? []).filter((i) => i.type === "bundleIds").map((b) => [b.id, b.attributes?.identifier])
  );
  return (Array.isArray(res.data) ? res.data : []).map((p) => ({
    resource: p,
    bundleId: bundleIds.get(p.relationships?.bundleId?.data?.id ?? "") ?? ""
  })).filter(({ bundleId }) => bundleId in PROFILE_NAMES);
}
async function profilesList() {
  const found = await squadquestProfiles();
  const rows = found.map(({ resource, bundleId }) => {
    const days = daysUntil(resource.attributes?.expirationDate);
    return {
      name: resource.attributes?.name,
      bundleId,
      type: resource.attributes?.profileType,
      state: resource.attributes?.profileState,
      expires: (resource.attributes?.expirationDate ?? "").slice(0, 10),
      daysLeft: days
    };
  });
  const problems = rows.filter((r) => r.type === APP_STORE_PROFILE).filter((r) => r.state !== "ACTIVE" || (r.daysLeft ?? 999) < 30).map(
    (r) => r.state !== "ACTIVE" ? `${r.name} is ${r.state}` : `${r.name} expires in ${r.daysLeft} days`
  );
  const missing = Object.entries(PROFILE_NAMES).filter(([bundleId]) => !rows.some((r) => r.bundleId === bundleId)).map(([bundleId, name]) => `no ${APP_STORE_PROFILE} profile for ${bundleId} (expected "${name}")`);
  return {
    profiles: rows,
    ...problems.length || missing.length ? {
      attention: [...problems, ...missing],
      help: [`Run \`${cliInvocation()} profiles regenerate\` to recreate them`]
    } : {}
  };
}
async function distributionCertificate() {
  const res = await requestAll("/v1/certificates?limit=200");
  const certs = (Array.isArray(res.data) ? res.data : []).filter(
    (c) => c.attributes?.certificateType === "DISTRIBUTION"
  );
  const sorted = certs.filter((c) => (daysUntil(c.attributes?.expirationDate) ?? -1) > 0).sort(
    (a, b) => (daysUntil(b.attributes?.expirationDate) ?? 0) - (daysUntil(a.attributes?.expirationDate) ?? 0)
  );
  const cert = sorted[0];
  if (!cert) {
    throw new AxiError("No valid distribution certificate", "no-distribution-cert", [
      "Create one in the Developer portal, then update APPLE_CERTIFICATE_BASE64 in GitHub secrets"
    ]);
  }
  return cert;
}
async function profilesRegenerate(args) {
  const only = args.includes("--bundle-id") ? args[args.indexOf("--bundle-id") + 1] : void 0;
  if (only && !(only in PROFILE_NAMES)) {
    throw new AxiError(`Unknown bundle id ${only}`, "unknown-bundle-id", [
      `Known: ${Object.keys(PROFILE_NAMES).join(", ")}`
    ]);
  }
  const targets = only ? [only] : Object.keys(PROFILE_NAMES);
  const cert = await distributionCertificate();
  const existing = await squadquestProfiles();
  const bundleRes = await requestAll(
    `/v1/bundleIds?filter%5Bidentifier%5D=${encodeURIComponent(APP_BUNDLE_ID)}&limit=200`
  );
  const bundleIdResources = new Map(
    (Array.isArray(bundleRes.data) ? bundleRes.data : []).map((b) => [
      b.attributes?.identifier,
      b.id
    ])
  );
  const results = [];
  for (const bundleId of targets) {
    const name = PROFILE_NAMES[bundleId];
    const resourceId = bundleIdResources.get(bundleId);
    if (!resourceId) {
      throw new AxiError(`Bundle id ${bundleId} is not registered`, "bundle-id-not-found");
    }
    for (const { resource, bundleId: existingBundle } of existing) {
      if (existingBundle === bundleId && resource.attributes?.profileType === APP_STORE_PROFILE) {
        await request("DELETE", `/v1/profiles/${resource.id}`);
      }
    }
    const created = await request("POST", "/v1/profiles", {
      data: {
        type: "profiles",
        attributes: { name, profileType: APP_STORE_PROFILE },
        relationships: {
          bundleId: { data: { id: resourceId, type: "bundleIds" } },
          certificates: { data: [{ id: cert.id, type: "certificates" }] }
        }
      }
    });
    const attrs = created.data.attributes ?? {};
    results.push({
      name: attrs.name,
      bundleId,
      state: attrs.profileState,
      expires: (attrs.expirationDate ?? "").slice(0, 10)
    });
  }
  return {
    regenerated: results,
    certificate: cert.attributes?.name,
    note: "Names are unchanged, so ExportOptions.plist and the workflow need no edit"
  };
}
async function certsList() {
  const res = await requestAll("/v1/certificates?limit=200");
  const rows = (Array.isArray(res.data) ? res.data : []).map((c) => ({
    name: c.attributes?.name,
    type: c.attributes?.certificateType,
    expires: (c.attributes?.expirationDate ?? "").slice(0, 10),
    daysLeft: daysUntil(c.attributes?.expirationDate)
  })).sort((a, b) => (a.daysLeft ?? 0) - (b.daysLeft ?? 0));
  const expiring = rows.filter(
    (r) => r.type === "DISTRIBUTION" && (r.daysLeft ?? 999) < 60
  );
  return {
    certificates: rows,
    ...expiring.length ? {
      attention: expiring.map(
        (r) => `${r.name} expires in ${r.daysLeft} days \u2014 re-export the .p12 and update APPLE_CERTIFICATE_BASE64, then regenerate profiles`
      )
    } : {}
  };
}
async function devicesList() {
  const res = await requestAll("/v1/devices?limit=200");
  const rows = (Array.isArray(res.data) ? res.data : []).filter((d) => d.attributes?.status === "ENABLED").map((d) => ({
    name: d.attributes?.name,
    platform: d.attributes?.platform,
    udid: d.attributes?.udid
  }));
  return { devices: rows, count: rows.length };
}
async function devicesAdd(args) {
  const [name, udid] = args;
  if (!name || !udid) throw new AxiError("Usage: devices add <name> <udid>", "usage");
  const res = await request("POST", "/v1/devices", {
    data: {
      type: "devices",
      attributes: { name, udid, platform: "IOS" }
    }
  });
  const attrs = res.data.attributes ?? {};
  return {
    added: { name: attrs.name, udid: attrs.udid, status: attrs.status },
    help: [
      `Run \`${cliInvocation()} profiles regenerate\` so development profiles pick up the new device`
    ]
  };
}

// src/cli/commands/home.ts
function helpLines() {
  const cli = cliInvocation();
  return [
    `Run \`${cli} builds\` to see recent TestFlight builds`,
    `Run \`${cli} version list\` to see App Store versions and their state`,
    `Run \`${cli} profiles list\` to check signing assets before a release`,
    `Run \`${cli} --help\` for the full command list`
  ];
}
async function liveState() {
  const app = await getApp();
  const [versionsRes, buildsRes, profilesRes] = await Promise.all([
    request("GET", `/v1/apps/${app.id}/appStoreVersions?limit=3`),
    request("GET", `/v1/builds?filter%5Bapp%5D=${app.id}&sort=-version&limit=1`),
    requestAll("/v1/profiles?limit=200")
  ]);
  const versions2 = Array.isArray(versionsRes.data) ? versionsRes.data : [];
  const live = versions2.find((v) => v.attributes?.appStoreState === "READY_FOR_SALE");
  const inFlight = versions2.find((v) => v.attributes?.appStoreState !== "READY_FOR_SALE");
  const latestBuild = (Array.isArray(buildsRes.data) ? buildsRes.data : [])[0];
  const expiringSoon = (Array.isArray(profilesRes.data) ? profilesRes.data : []).filter((p) => RELEASE_PROFILE_NAMES.includes(p.attributes?.name ?? "")).filter((p) => {
    const days = (new Date(p.attributes?.expirationDate ?? 0).getTime() - Date.now()) / 864e5;
    return p.attributes?.profileState !== "ACTIVE" || days < 30;
  }).map((p) => p.attributes?.name);
  return {
    app: {
      name: app.attributes?.name,
      bundleId: APP_BUNDLE_ID,
      live: live?.attributes?.versionString ?? "\u2014"
    },
    ...inFlight ? {
      inFlight: {
        version: inFlight.attributes?.versionString,
        state: inFlight.attributes?.appStoreState
      }
    } : {},
    ...latestBuild ? {
      latestBuild: {
        build: latestBuild.attributes?.version,
        state: latestBuild.attributes?.processingState
      }
    } : {},
    ...expiringSoon.length ? { signingAttention: expiringSoon } : {}
  };
}
async function home() {
  let state;
  try {
    state = await liveState();
  } catch (error) {
    state = {
      status: "not configured",
      detail: error instanceof Error ? error.message : String(error),
      setup: [
        `Put a team API key at ${KEY_DIR}/AuthKey_<id>.p8 (chmod 600)`,
        `Set APPSTORE_ISSUER_ID, or write it to ${KEY_DIR}/issuer_id`
      ]
    };
  }
  return { description: DESCRIPTION, ...state, help: helpLines() };
}
function topLevelHelp() {
  const lines = [DESCRIPTION, "", "Commands:"];
  for (const group2 of COMMAND_GROUPS) {
    lines.push("", `  ${group2.group}:`);
    for (const c of group2.commands) {
      lines.push(`    ${c.usage.padEnd(52)} ${c.summary}`);
    }
  }
  lines.push("", `Invoke as: ${cliInvocation()} <command>`);
  return lines.join("\n");
}

// src/cli/commands/hook.ts
import { fileURLToPath as fileURLToPath2 } from "node:url";
import { dirname as dirname3, resolve as resolve2 } from "node:path";
var MARKER = "squadquest-appstore";
function projectDir() {
  const bundle = fileURLToPath2(import.meta.url);
  return resolve2(dirname3(bundle), "..", "..", "..", "..");
}
function scopeOf(args) {
  return args.includes("--global") ? { scope: "user" } : { scope: "project", projectDir: projectDir() };
}
async function hook(args) {
  const action = args[0];
  const scope = scopeOf(args);
  const execPath = cliInvocation().replace(/^node /, "").replace(/^~/, process.env.HOME ?? "~");
  if (action === "install") {
    installSessionStartHooks({ marker: MARKER, execPath, ...scope });
    return {
      installed: { marker: MARKER, scope: scope.scope },
      note: "New sessions will show the App Store view on start"
    };
  }
  if (action === "uninstall") {
    uninstallSessionStartHooks({ marker: MARKER, execPath, ...scope });
    return { uninstalled: { marker: MARKER, scope: scope.scope } };
  }
  if (action === "status" || action === void 0) {
    const status = sessionStartHookStatus({ marker: MARKER, execPath, ...scope });
    return {
      hook: {
        marker: status.marker,
        scope: status.scope,
        claude: status.claude.installed,
        path: status.claude.path
      },
      help: [`Run \`${cliInvocation()} hook install\` to enable it for this repo`]
    };
  }
  throw new AxiError(`Unknown hook action '${action}'`, "unknown-hook-action", [
    "Use install, uninstall or status"
  ]);
}

// src/cli/commands/release.ts
import { execFileSync } from "node:child_process";
import { readFileSync as readFileSync4 } from "node:fs";
var PLATFORM = "IOS";
function flag(args, name) {
  const i = args.indexOf(`--${name}`);
  return i >= 0 ? args[i + 1] : void 0;
}
function has(args, name) {
  return args.includes(`--${name}`);
}
async function builds(args) {
  const app = await getApp();
  const limit = Number(flag(args, "limit") ?? 10);
  const res = await request(
    "GET",
    `/v1/builds?filter%5Bapp%5D=${app.id}&sort=-version&limit=${Math.min(limit, 200)}`
  );
  const rows = (Array.isArray(res.data) ? res.data : []).map((b) => ({
    build: b.attributes?.version,
    state: b.attributes?.processingState,
    expired: b.attributes?.expired ? "yes" : "no",
    uploaded: (b.attributes?.uploadedDate ?? "").slice(0, 16).replace("T", " ")
  }));
  if (rows.length === 0) {
    return {
      builds: [],
      note: "No builds found. Publish a release, or run the workflow with upload_to_testflight enabled."
    };
  }
  return {
    builds: rows,
    help: [
      `Run \`${cliInvocation()} build attach <version> <build>\` to bind one to a version`
    ]
  };
}
async function versions(appId, limit = 20) {
  return requestAll(
    `/v1/apps/${appId}/appStoreVersions?limit=${Math.min(limit, 200)}&include=build`
  );
}
async function versionList(args) {
  const app = await getApp();
  const limit = Number(flag(args, "limit") ?? 10);
  const res = await versions(app.id, limit);
  const builds2 = new Map(
    (res.included ?? []).filter((i) => i.type === "builds").map((b) => [b.id, b])
  );
  const all = Array.isArray(res.data) ? res.data : [];
  const rows = all.slice(0, limit).map((v) => ({
    version: v.attributes?.versionString,
    state: v.attributes?.appStoreState,
    release: v.attributes?.releaseType,
    build: builds2.get(v.relationships?.build?.data?.id ?? "")?.attributes?.version ?? "\u2014"
  }));
  return { versions: rows, ...all.length > rows.length ? { total: all.length } : {} };
}
async function findVersion(appId, versionString) {
  const res = await versions(appId, 200);
  const match = (Array.isArray(res.data) ? res.data : []).find(
    (v) => v.attributes?.versionString === versionString
  );
  if (!match) {
    throw new AxiError(`No App Store version ${versionString}`, "version-not-found", [
      `Run \`${cliInvocation()} version list\` to see what exists`,
      `Run \`${cliInvocation()} version create ${versionString}\` to start it`
    ]);
  }
  return match;
}
async function versionShow(args) {
  const versionString = args[0];
  if (!versionString) throw new AxiError("Usage: version show <version>", "usage");
  const app = await getApp();
  const version = await findVersion(app.id, versionString);
  const locRes = await request(
    "GET",
    `/v1/appStoreVersions/${version.id}/appStoreVersionLocalizations?limit=50`
  );
  const locales = (Array.isArray(locRes.data) ? locRes.data : []).map((l) => ({
    locale: l.attributes?.locale,
    whatsNew: (l.attributes?.whatsNew ?? "").split("\n")[0]?.slice(0, 60) ?? ""
  }));
  let build = "\u2014";
  const buildId = version.relationships?.build?.data?.id;
  if (buildId) {
    const b = await request("GET", `/v1/builds/${buildId}`);
    build = b.data?.attributes?.version ?? "\u2014";
  }
  return {
    version: {
      version: version.attributes?.versionString,
      state: version.attributes?.appStoreState,
      releaseType: version.attributes?.releaseType,
      build
    },
    localizations: locales
  };
}
async function versionCreate(args) {
  const versionString = args[0];
  if (!versionString) throw new AxiError("Usage: version create <version>", "usage");
  const app = await getApp();
  const res = await request("POST", "/v1/appStoreVersions", {
    data: {
      type: "appStoreVersions",
      attributes: { platform: PLATFORM, versionString },
      relationships: { app: { data: { id: app.id, type: "apps" } } }
    }
  });
  const created = res.data;
  return {
    created: {
      version: created.attributes?.versionString,
      state: created.attributes?.appStoreState
    },
    help: [
      `Run \`${cliInvocation()} notes set ${versionString} --from-release v${versionString}\` to fill What's New`
    ]
  };
}
function notesFromRelease(tag) {
  let body;
  try {
    body = execFileSync(
      "gh",
      ["release", "view", tag, "--repo", "SquadQuest/SquadQuest", "--json", "body", "--jq", ".body"],
      { encoding: "utf8" }
    );
  } catch {
    throw new AxiError(`Couldn't read release ${tag}`, "release-not-found", [
      "Check the tag exists and gh is authenticated"
    ]);
  }
  const lines = body.split("\n");
  const start = lines.findIndex((l) => /^##\s+What'?s New/i.test(l));
  if (start === -1) {
    throw new AxiError(`Release ${tag} has no "## What's New" section`, "no-whats-new", [
      "Pass --file or --text instead"
    ]);
  }
  const rest = lines.slice(start + 1);
  const end = rest.findIndex((l) => /^##\s/.test(l));
  return (end === -1 ? rest : rest.slice(0, end)).join("\n").trim();
}
async function notesSet(args) {
  const versionString = args[0];
  if (!versionString) throw new AxiError("Usage: notes set <version> [source]", "usage");
  const file = flag(args, "file");
  const text = flag(args, "text");
  const fromRelease = flag(args, "from-release");
  let whatsNew;
  if (fromRelease) whatsNew = notesFromRelease(fromRelease);
  else if (file) whatsNew = readFileSync4(file, "utf8").trim();
  else if (text) whatsNew = text;
  else {
    throw new AxiError("Need one of --file, --text or --from-release", "usage", [
      `Run \`${cliInvocation()} notes set ${versionString} --from-release v${versionString}\` to reuse the GitHub release notes`
    ]);
  }
  if (whatsNew.length > 4e3) {
    throw new AxiError(
      `What's New is ${whatsNew.length} characters; the App Store allows 4000`,
      "notes-too-long"
    );
  }
  const app = await getApp();
  const version = await findVersion(app.id, versionString);
  const locRes = await request(
    "GET",
    `/v1/appStoreVersions/${version.id}/appStoreVersionLocalizations?limit=50`
  );
  const updated = [];
  for (const loc of Array.isArray(locRes.data) ? locRes.data : []) {
    await request("PATCH", `/v1/appStoreVersionLocalizations/${loc.id}`, {
      data: { id: loc.id, type: "appStoreVersionLocalizations", attributes: { whatsNew } }
    });
    updated.push(loc.attributes?.locale);
  }
  return { version: versionString, locales: updated, characters: whatsNew.length };
}
async function buildAttach(args) {
  const [versionString, buildNumber] = args;
  if (!versionString || !buildNumber) {
    throw new AxiError("Usage: build attach <version> <build>", "usage");
  }
  const app = await getApp();
  const version = await findVersion(app.id, versionString);
  const res = await request(
    "GET",
    `/v1/builds?filter%5Bapp%5D=${app.id}&filter%5Bversion%5D=${encodeURIComponent(buildNumber)}&limit=10`
  );
  const build = (Array.isArray(res.data) ? res.data : [])[0];
  if (!build) {
    throw new AxiError(`No build ${buildNumber}`, "build-not-found", [
      `Run \`${cliInvocation()} builds\` to see what has been uploaded`
    ]);
  }
  const state = build.attributes?.processingState;
  if (state !== "VALID") {
    throw new AxiError(`Build ${buildNumber} is ${state}, not VALID`, "build-not-ready", [
      "Apple is still processing it \u2014 wait and try again"
    ]);
  }
  await request("PATCH", `/v1/appStoreVersions/${version.id}/relationships/build`, {
    data: { id: build.id, type: "builds" }
  });
  return {
    attached: { version: versionString, build: buildNumber },
    help: [`Run \`${cliInvocation()} submit ${versionString}\` when the metadata is ready`]
  };
}
async function submit(args) {
  const versionString = args[0];
  if (!versionString) throw new AxiError("Usage: submit <version> [--yes]", "usage");
  const app = await getApp();
  const version = await findVersion(app.id, versionString);
  if (!has(args, "yes")) {
    const detail = await versionShow([versionString]);
    return {
      wouldSubmit: detail.version,
      localizations: detail.localizations,
      confirm: `Re-run with --yes to submit ${versionString} for App Store review`
    };
  }
  const sub = await request("POST", "/v1/reviewSubmissions", {
    data: {
      type: "reviewSubmissions",
      attributes: { platform: PLATFORM },
      relationships: { app: { data: { id: app.id, type: "apps" } } }
    }
  });
  const submissionId = sub.data.id;
  await request("POST", "/v1/reviewSubmissionItems", {
    data: {
      type: "reviewSubmissionItems",
      relationships: {
        reviewSubmission: { data: { id: submissionId, type: "reviewSubmissions" } },
        appStoreVersion: { data: { id: version.id, type: "appStoreVersions" } }
      }
    }
  });
  await request("PATCH", `/v1/reviewSubmissions/${submissionId}`, {
    data: { id: submissionId, type: "reviewSubmissions", attributes: { submitted: true } }
  });
  return {
    submitted: { version: versionString, submissionId },
    note: "Apple will email as review progresses; check state with `version show`"
  };
}
async function releaseVersion(args) {
  const versionString = args[0];
  if (!versionString) throw new AxiError("Usage: release <version> [--yes]", "usage");
  const app = await getApp();
  const version = await findVersion(app.id, versionString);
  const state = version.attributes?.appStoreState;
  if (!has(args, "yes")) {
    return {
      wouldRelease: { version: versionString, state },
      confirm: `Re-run with --yes to release ${versionString} to the App Store`
    };
  }
  if (state !== "PENDING_DEVELOPER_RELEASE") {
    throw new AxiError(
      `Version ${versionString} is ${state}, not waiting for release`,
      "not-releasable",
      ["Only an approved version held for manual release can be released this way"]
    );
  }
  await request("POST", "/v1/appStoreVersionReleaseRequests", {
    data: {
      type: "appStoreVersionReleaseRequests",
      relationships: {
        appStoreVersion: { data: { id: version.id, type: "appStoreVersions" } }
      }
    }
  });
  return { released: { version: versionString } };
}

// src/cli/cli.ts
var VERSION = true ? "v1.46.0-8-g6c48f5f" : "dev";
function group(name, actions) {
  return (args) => {
    const action = args[0];
    const handler = action ? actions[action] : void 0;
    if (!handler) {
      throw new AxiError(
        action ? `Unknown ${name} action '${action}'` : `${name} needs an action`,
        `unknown-${name}-action`,
        [`Available: ${Object.keys(actions).join(", ")}`]
      );
    }
    return handler(args.slice(1));
  };
}
async function main(argv = process.argv.slice(2)) {
  await runAxiCli({
    description: DESCRIPTION,
    version: VERSION,
    argv,
    topLevelHelp: topLevelHelp(),
    home: () => home(),
    commands: {
      home: () => home(),
      hook: (args) => hook(args),
      builds: (args) => builds(args),
      version: group("version", {
        list: versionList,
        create: versionCreate,
        show: versionShow
      }),
      notes: group("notes", { set: notesSet }),
      build: group("build", { attach: buildAttach }),
      submit: (args) => submit(args),
      release: (args) => releaseVersion(args),
      profiles: group("profiles", {
        list: () => profilesList(),
        regenerate: profilesRegenerate
      }),
      certs: group("certs", { list: () => certsList() }),
      devices: group("devices", { list: () => devicesList(), add: devicesAdd })
    }
  });
}

// src/cli/bin.ts
await main();
