create table
  public.friends (
    id bigint generated by default as identity,
    created_at timestamp with time zone not null default now(),
    actioned_at timestamp with time zone null,
    requester uuid null,
    requestee uuid null,
    status public.friend_status null default 'requested'::friend_status,
    constraint friends_pkey primary key (id),
    constraint friends_requester_fkey foreign key (requester) references users (id),
    constraint friends_requestee_fkey foreign key (requestee) references users (id)
  );
