name: 'PR: Test Flutter'

on:
  push:
    branches:
      - '**'
      - '!main'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: 'read'

jobs:
  pr-test:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Set up Flutter Version Management CLI
        uses: flutter-actions/setup-fvm@v1.0

      - name: Install Flutter SDK
        run: fvm install

      - name: Activate Flutter SDK
        run: fvm use --skip-pub-get

      - name: Get depedencies
        run: fvm flutter pub get

      - name: Generate .env
        run: touch .env

      - name: Run tests
        run: fvm flutter test

      - name: Upload test failure artifacts
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: test-failures
          path: test/**/failures/
          if-no-files-found: ignore
