name: 'Test Workflow'

on:
  workflow_dispatch:

jobs:
  test:

    runs-on: ubuntu-latest
    steps:

    - uses: mxschmitt/action-tmate@v3
      env:
        SUPABASE_GITHUB_RELEASE_ACTION_TOKEN: ${{ secrets.SUPABASE_GITHUB_RELEASE_ACTION_TOKEN }}

